### ISSUE TITLE
Setup.py fails if jackd is not installed

### ISSUE THREAD

**Issue by marierm** [belangeo/pyo#100]
On systems like Arch, it is possible to have jack2-dbus installed without the jackd.  If it is the case, the setup script fails with the following error.  Changing the function get_jack_api() on line 35 of setup.py temporarily solves the issue, but it is certainly not a permanent fix.

```
def get_jack_api():
    return "JACK_OLD_API"
```

```
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    macros.append((get_jack_api(), None))
  File "setup.py", line 35, in get_jack_api
    output = subprocess.Popen(["jackd", "-V"], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'jackd'
```

**Comment by belangeo** [comment]
I wrapped the query for jack version inside a try-except statement which defaults to the old api if it fails. I can't find a way to retrieve the version from jack_control but the package says it is 1.9.10 so I think that should be enough for now!
