### ISSUE TITLE
Building pyo with Jack support on WIndows

### ISSUE THREAD

**Issue by YoomarXD** [belangeo/pyo#101]
Using pyo 0.8.4 for Python 3.5 on Windows 10.
(because I couldn't manage to make the 0.8.6 version work)

I can not build pyo with Jack support. 
Everytime I try it throws:
```
PS D:\OneDrive\Documents\Python\Librerías\pyo-master-0.8.4> python setup.py build --use-jack --use-coreaudio --use-double
Traceback (most recent call last):
  File "setup.py", line 123, in <module>
    macros.append((get_jack_api(), None))
  File "setup.py", line 35, in get_jack_api
    output = subprocess.Popen(["jackd", "-V"], stdout=subprocess.PIPE)
  File "C:\Users\Yooma\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Yooma\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```
I want Jack support to make the [multicore examples](http://ajaxsoundstudio.com/pyodoc/examples/18-multicore/index.html) work. (There is a typo btw, it says 18-multicore instead of 08-multicore).

How do I fix it?
Could you provide a pre-built pyo with Jack support included?

**Comment by belangeo** [comment]
Hi,
I never tried jack on Windows so I don't know if the code will work as is... I'll try to make it work ASAP. If you want to give it a try, you could change the function `get_jack_api()` in setup.py to return "JACK_NEW_API" (based on version number on jack download page):

`
def get_jack_api():
    return "JACK_NEW_API"
`
Then, you'll probably have to tell the setup where are the jack headers and libraries (lines 165 to 171).

18-multicore is not a typo, there is a bunch of examples categories which will go between 07-effects and 18-multicore! Stay tuned!

**Comment by belangeo** [comment]
Closing this issue as I'm pretty sure now that Jack will never work properly on Windows (it does not work anymore on newer macs, and for now, nobody is taking over its development apart for Linux maintenance). I will put my little free time to spend on pyo on other projects.
