### ISSUE TITLE
Closing jack server provokes error in pyo

### ISSUE THREAD

**Issue by bielaszewski** [belangeo/pyo#109]
If jack is stopped (from qjackctl for example) an error message from is displayed on Pyo's stdout/stderr:
`   _JACK error: Cannot callback the server in notification thread!_`
Followed by an error from  Pyo:
`   _jack error: cannot deactivate jack client._`

This was observed in release 0.8.7 running on Linux (ubuntu studio build).

The simplest Pyo app shows the error:
```
   _from pyo import *
   s= Server( audio='jack').boot()
   s.gui( locals() )_
```

**Details**

1) assume jack is already running. started by say, qjackctl
2) start pyo app
3) from qjackctl stop jack
4) the error messages described above are produced,  the Pyo app appears hung.

**Cause**
Pyo's jack shutdown callback  _jack_shutdown_cb()_   in  ad_jack.c
calls _Server_shutdown()_   in servermodule.c
which calls Server_jack_deinit()  ad_jack.c
which calls jack_deactivate()
resulting in error messages above.

The call to jack_deactivate()  provokes jack's message:
_JACK error: Cannot callback the server in notification thread!_
The shutdown calling sequence would need to be called from some thread other than 
the jack shutdown callback to avoid this condition.

**Comment by belangeo** [comment]
Fixed in sources.

**Comment by bielaszewski** [comment]
thanks!  i'll pull the changes.
