### ISSUE TITLE
md_portmidi.h error

### ISSUE THREAD

**Issue by RoberWare** [belangeo/pyo#113]
When I try to install it:
>python setup.py install

This error appears:

> roberto@roberto-MS-7808 ~/Programas/Python/GUITARLOOPER/pyo-master $ python setup.py install
running install
running build
running build_py
file pyo.py (for module pyo) not found
file pyo.py (for module pyo) not found
running build_ext
building '_pyo' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_PORTAUDIO -DUSE_PORTMIDI -DUSE_OSC -Iinclude -I/usr/local/include -I/usr/include/python2.7 -c src/engine/pyomodule.c -o build/temp.linux-x86_64-2.7/src/engine/pyomodule.o -Wno-strict-prototypes -Wno-strict-aliasing -O3 -g0 -DNDEBUG
In file included from src/engine/pyomodule.c:56:0:
include/md_portmidi.h:25:22: **fatal error: portmidi.h: There is no file or directory**
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by belangeo** [comment]
Portmidi must be installed (-dev package). All dependencies are listed on the "compiling from sources" page:

http://ajaxsoundstudio.com/pyodoc/compiling.html

**Comment by RoberWare** [comment]
Thanks! It finally built!.
Sorry for the stupid issue.

2017-11-22 3:17 GMT+01:00 Olivier Bélanger <notifications@github.com>:
