### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by beta2k** [belangeo/pyo#114]
![image](https://user-images.githubusercontent.com/1133118/33288105-60ef7d14-d3bb-11e7-9e2e-3c543bd5158a.png)

I get this error on Windows 7 Ultimate 64Bit when I try to launch E-Pyo.exe. I have downloaded and tried with both:

- pyo_0.8.8_py3.5_setup.exe : Windows (Win 7 and higher), python 3.5, 32-bit
- pyo_0.8.8_py3.6_setup.exe : Windows (Win 7 and higher), python 3.6, 32-bit

I have the Anaconda Python 3.6 distribution installed. 

I also tried to manually copy the content of `C:\Python36-32\Lib\site-packages` to `C:\ProgramData\Anaconda3\Lib\site-packages`, but it did not help. 

How can I run E-Pyo.exe ?

**Comment by beta2k** [comment]
I solved this by putting python.exe in my PATH variable.

**Comment by YuleZhang** [comment]
thank you
