### ISSUE TITLE
Issue running on windows10 64 bit, python 2.7 32 bit, pyo v0.8.8

### ISSUE THREAD

**Issue by VectorLane** [belangeo/pyo#116]
Hi,

Quite new to this... Patience please...
I've installed python 2.7 (Anaconda distro) v32bit followed by pyo 0.8.8.

From the CMD window, I have typed 'python'. All OK.
Then I typed 'from pyo import *'
Received: pyo version 0.8.8 (uses single  precision)  #This is copied from the <>code page here on github
Then I typed: s = Server().boot()
Received: portaudio error in Pa_openstream: Invalid device
               portaudio error invalid device portaudio error in Pa_close stream (Pa_deinit): portaudio not initialized
               portaudio error in Pa_terminate ( pa_deinit): Port audio not initialized

I've notice that if i type only:
s = Server()
I receive no error. It seems that the 'boot' is causing the error.

I'll mention that both input and output of audio (realtek) is configured correctly, enabled, no audio effects running...

Any hints to a solution?

I have tried both ASIO (focusrite) as well as internal udio device (RealTek, its a laptop) and set it to default input and output.
Also followed this link:
https://groups.google.com/forum/#!topic/pyo-discuss/vRN6lLgdNGM

Is there a way to get a list of working audio servers for correct naming (ASIO, asio, - ASIO, etc.) ?

Appreciated !

**Comment by belangeo** [comment]
Probably a mismatch between pyo's sampling rate (defaults to 44100) and system's sampling rate (maybe 48000).

Did you take a look at this page in the documentation:
http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html

Server's manual:
http://ajaxsoundstudio.com/pyodoc/api/classes/server.html

**Comment by VectorLane** [comment]
Many thanks for the fast response !

After playing with it and reading the links, I could get it working by setting:
s = Server(48000).boot()

This works from the CMD console. I still could not get it running from the IDE (Spyder) on which I receive this error set three times following:

_**Traceback (most recent call last):

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\core\formatters.py", line 699, in __call__
    printer.pretty(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 368, in pretty
    return self.type_pprinters[cls](obj, self, cycle)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 705, in _repr_pprint
    p.text(output_line)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 211, in text
    self.output.write(obj)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\lib\pretty.py", line 119, in write
    cast_unicode(text, encoding=get_stream_enc(sys.stdout)))

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 27, in cast_unicode
    return decode(s, encoding)

  File "C:\ProgramData\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 18, in decode
    return s.decode(encoding, "replace")

LookupError: unknown encoding: cp0**_

Any hint on this ?

**Comment by belangeo** [comment]
This error does not seem to be related to pyo... Can you post the program you're trying to run?

**Comment by VectorLane** [comment]
I'm just trying to run a program (module/script) which has two lines:
from pyo import *
s = Server(48000).boot()

Those two lines work OK from the CMD window, but not from Spyder IDE, which otherwise perfroms OK (other programs).
Maybe I can run some basic pyo requests to see that Spyder is accessin pyo correctly ?
If I run only the upper line (from pyo import *) no error is given...

Appreciated

**Comment by VectorLane** [comment]
Update:

I simply uninstalled Anaconda/Spyder/Python27/Pyo and re-installed everything.
Now it works.

Thank you for your help and fast response on this topic. Appreciated !

**Comment by belangeo** [comment]
Glad it works!
