### ISSUE TITLE
Segmentation fault: 11  

### ISSUE THREAD

**Issue by AnasGhrab** [belangeo/pyo#118]
Hi !

When I use the simple code below, I do not understand why I get this error : 
```
=== Output log of process "test2.py", launched: "03 Feb 2018 16:37:21" ===
pyo version 0.8.8 (uses single precision)
/bin/sh: line 1:  1067 Segmentation fault: 11  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u "/Users/anas/.epyo/epyo_tempfile.py"
```

```
from pyo import *

s = Server().boot().start()

lfo = Sine(0.1, 100)
a = Sine(freq = 100+lfo, mul = 0.1)
a.out()

s.gui(locals())
```

**Comment by belangeo** [comment]
The Server tries to open both audio input and output devices by default. Is there an audio input defined on the system ? Newer macpro don't have one by default...!
Can you try with this Server initialization:

`s = Server(duplex=False).boot().start()`

BTW, you give a value of 100 to the phase argument of the Sine object. The phase is between 0 and 1. I guess you want something like :

`lfo = Sine(0.1, mul=100)`

**Comment by AnasGhrab** [comment]
I understand now why I got a similar error on a mac-mini which doesn't have any default input. It shouldn't give an error...

Best,

--
Anas
