### ISSUE TITLE
Installing on Mac with Anaconda

### ISSUE THREAD

**Issue by jarmitage** [belangeo/pyo#122]
I noticed in #115 you mention that pyo does not detect Anaconda installs of Python.

Indeed I've just installed 0.9.0 and Python cannot find the pyo module.

In #115 you say to choose the install location, but the Mac installer does not allow you to choose a path.

Any idea how I can work around this?

**Comment by vism2889** [comment]
using `pythonw filename.py' is a quick work around, but i've been getting a lot of errors over the past few days since playing with the module more, dunno if its related to that.

**Comment by jarmitage** [comment]
@belangeo that path is correct, so that's strange that I can't see Pyo there.

I am currently using `python3.5` though, should that make a difference?

Maybe I should try installing from source?
