### ISSUE TITLE
Zyne installation

### ISSUE THREAD

**Issue by svatty89** [belangeo/pyo#124]
Hi there. Please, can you give me an answer how to install zyne modular synth using pyo. So firstly i should install pyo and then what command should i use? Thanks in advance. Update. Forgot to mention. My OS - Windows 7.

**Comment by belangeo** [comment]
I am actually working on a revamp version of Zyne (not tested at all on Windows). It now uses python3 and wxpython phoenix (4.0.1). If these and pyo are installed, you can clone zyne repo and start it with from the command prompt:

    git clone https://github.com/belangeo/zyne.git
    cd zyne
    python3 Zyne.py

I hope to be able to release the new version by the end of the summer!

**Comment by belangeo** [comment]
Not an issue. Closing.
