### ISSUE TITLE
pyo with pycharm

### ISSUE THREAD

**Issue by ShiriKuz** [belangeo/pyo#125]
hi,
is it possible to have pyo on a pychram project in windows 10?
i tried importing pyo but it doesn't seem to work.
thanks.

**Comment by belangeo** [comment]
I don't use it myself but pycharm is just an IDE, there is no reason you can't use pyo in a project for which you use pycharm to develop. The only thing I see is that pycharm target a different version of python that the one where pyo is installed...

**Comment by katdob** [comment]
@ShiriKuz is this still an issue for you? I'm also a pycharm user, maybe I can help.

**Comment by andresilloFIE** [comment]
> 
> 
> @ShiriKuz is this still an issue for you? I'm also a pycharm user, maybe I can help.

Hi I also use Pycharm and have the same issue... can you help me?

**Comment by ShiriKuz** [comment]
Hi,
For me It worked eventually. What is the code you are trying to run? Maybe I can help.

**Comment by ShiriKuz** [comment]
@andresilloFIE 
For me It worked eventually. What is the code you are trying to run? Maybe I can help.

**Comment by NickADD** [comment]
I see this was last discussed exactly a year ago today.  Hopefully y'all are still around....

I am using pyCharm also.  I can't get the basic examples given in the docs to produce a sound, though my Mac does ask me to allow access to the microphone when I run the script.  It also gives me this strange error:

2020-02-25 17:17:44.026 Python[81236:27401405] Error loading /Library/Audio/Plug-Ins/HAL/SeratoVirtualAudioPlugIn.plugin/Contents/MacOS/SeratoVirtualAudioPlugIn:  dlopen(/Library/Audio/Plug-Ins/HAL/SeratoVirtualAudioPlugIn.plugin/Contents/MacOS/SeratoVirtualAudioPlugIn, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/SeratoVirtualAudioPlugIn.plugin/Contents/MacOS/SeratoVirtualAudioPlugIn: mach-o, but wrong architecture
	/Library/Audio/Plug-Ins/HAL/SeratoVirtualAudioPlugIn.plugin/Contents/MacOS/SeratoVirtualAudioPlugIn: mach-o, but wrong architecture
2020-02-25 17:17:44.026 Python[81236:27401405] Cannot find function pointer New_SHP_PlugIn for factory 834FC054-C1CC-11D6-BD01-00039315CD46 in CFBundle/CFPlugIn 0x7fb7311269e0 </Library/Audio/Plug-Ins/HAL/SeratoVirtualAudioPlugIn.plugin> (bundle, not loaded)


Anyone have any idea what's going on here?  Why is it looking for these plug-ins?  What is a 'function pointer?'

Thanks for looking.

**Comment by belangeo** [comment]
Hi,

I just installed PyCharm on a MacPro High Sierra (10.13.6) and I had no problem running and getting sound from pyo. I used python 3.8 from python.org installed system-wide.

The error from the plugin loading tells you that there is an architecture mismatch (plugin 32-bit / pycharm 64-bit or plugin 64-bit / pycharm 32-bit).

**Comment by NickADD** [comment]
Well I guess I better learn what an architecture mismatch is.  Thanks for responding.
