### ISSUE TITLE
Pyo load and process existing wav files

### ISSUE THREAD

**Issue by whosedaddy0** [belangeo/pyo#126]
It seems SfPlayer is an api for playing a soundfile. I'm wondering if there is an api which loads wav as a PyoObject. I looked through the documentation and couldn't find it.

**Comment by belangeo** [comment]
I think what you are looking for is the [SndTable](http://ajaxsoundstudio.com/pyodoc/api/classes/tables.html#sndtable) object!

**Comment by whosedaddy0** [comment]
Thanks for the advice. The SndTable object does load a wav file, but it's loaded as a PyoTableObject. I wanna apply freeverb on the audio clip, but freeverb only accepts PyoObject as input. Is there any way to convert PyoTableObject into PyoObject or any other methods to this problem?

**Comment by whosedaddy0** [comment]
Hi actually the greatest problem for me is my console doesn't response. Here is my code.

from pyo import *
import glob

files = glob.glob('E:/note_database/soundfiles/*')
save = 'E:/note_database/soundfiles_2/'

print(1)
s = Server()
s.boot()
s.start()
print(1)
sfL = SfPlayer(files[0], speed=1, mul=0.5).out()
savefile(sfL, save+files[0].split('\\')[1])

The console outputs the first (1), but doesn't print the second (1). It's because it's after s=Server(). The console didn't give me feedbacks on later codes too. The PyoObject is not saved, but there's no error reported in the console.

**Comment by whosedaddy0** [comment]
I found that the kernel is dead when python runs s.boot()

This is why the codes after s.boot() won't run. Is there any way to fix it?

**Comment by whosedaddy0** [comment]
I fix the problem by reinstalling pyo and setting winhost="asio".

But still I don't find a way to process existing sound files. Freeverb is unable to process PyoTableObject, but I don't find a way to load wav files as PyoObject.

**Comment by whosedaddy0** [comment]
I just found an amazing google group discussion solves me problem.

https://groups.google.com/forum/#!topic/pyo-discuss/LdFdCRjTtF4

Thanks for paying attention to user's questions so much. Pyo is an excellent library!

**Comment by belangeo** [comment]
> I fix the problem by reinstalling pyo and setting winhost="asio".

Yes, on Windows, you have to carefully choose the audio driver. If your soundcard has an ASIO driver, it's probably your best shot. If not, "directsound" is the safest one. The default is "wasapi".

The folder [examples](https://github.com/belangeo/pyo/tree/master/examples) in the sources is a good place to start with pyo!
