### ISSUE TITLE
Pyo embedded in Juce

### ISSUE THREAD

**Issue by JVanBuskirk** [belangeo/pyo#127]
Hi Olivier,
   Embedding pyo with the Juce framework crashes the host with pyo 0.90 and 0.89.  Everything works really well is pyo 0.88.  I hope use several Plugins developed in pyo with my students this year.  Once I have the bugs worked out, I will post them.

Jeremy

**Comment by belangeo** [comment]
Can you send me the crash reports?

**Comment by JVanBuskirk** [comment]
I reinstalled Pyo 0.90.  The Plugins are crashing Reaper and Juce's Audio Plugin Host, but no crash log.  Just the spinning color wheel.  After reinstalling 0.88 everything works, I did not recompile the plugins.  I've tried this a few times.  Same crashes with Pyo 0.89.

I found two older crash logs which I think were created because of this issue, but I can't recreate the crash logs tonight.
[AudioPluginHost_2018-07-22-203702.txt](https://github.com/belangeo/pyo/files/2221775/AudioPluginHost_2018-07-22-203702.txt)
[REAPER_2018-06-30-202828.txt](https://github.com/belangeo/pyo/files/2221776/REAPER_2018-06-30-202828.txt)

**Comment by belangeo** [comment]
Did you ever try to recompile your plugins with 0.8.9 or 0.9.0 ? I don't think a plugin compiled against pyo 0.8.8 will run with 0.8.9 or 0.9.0 (there were changes in m_pyo.h between these versions).

p.s.: I will make a new release before the end of the summer!

**Comment by JVanBuskirk** [comment]
I wrote a new plugin this weekend compiled with the source files from pyo 0.90.  It will not run with 0.90, but if I run it with 0.88, it works well.  Do you want me to share the Juce project?

**Comment by belangeo** [comment]
I made some changes recently to the embedded/juce framework (after 0.9.0 release). If you want to send me your project, I can test to see if these changes resolve the problem.

**Comment by JVanBuskirk** [comment]
Here is a link to the newest plugin.  I used Juce's GUI Editor for this one, but the issue happens with all the plugins. I think I compiled it with the updated pyo embedded files from 6/17.  I've included them in the repository to make sure.
https://github.com/JVanBuskirk/PluckSynth/

Thank you for your looking at the issue.  If there is any way I can help spread the word about pyo, let me know.  Last year I switched to using pyo in my classes.  I will continue again this year.

**Comment by belangeo** [comment]
Hi Jeremy,
I just tried your plugin (only VST2) on my debian computer and everything works fine (after adding the header path and library link for python). Your problem, I think, is the synchronization between your m_pyo.h file and the compiled pyo on your computer. I run diff between your file and the one that is in the repo right now and there is no difference, which means that your header file assumes changes that are not released yet. 
The simplest way of handling this, I guess, is to stick with 0.8.8 until the next release (a couple of weeks).

**Comment by JVanBuskirk** [comment]
Got it.  Thanks again.  Looking forward to the next release.

**Comment by JVanBuskirk** [comment]
Everything is working really well with 0.91.  Thanks.  The list plug-ins I've created with Juce ad Pyo is growing.  I'll be posting more soon.

**Comment by belangeo** [comment]
Excellent!
