### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by Paititi** [belangeo/pyo#133]
Hey, I compiled from source on arch and unable to boot server here's the message I got:

> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

Why is it asking for jack if I compiled without it?
And if I run with jack the message is:

> ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave

**Comment by belangeo** [comment]
Hi,
First you can ignore ALSA warnings. Then, the messages saying that jack server is not running probably come from portaudio trying to start jack.
A possible problem is a number if channels mismatch between the system and the pyo's Server. By default pyo's Server ask for two channels for both input and output (`duplex` argument). Be sure there is at least two input channels configured in the system.

When you run with jack, does your program work after printing those warnings?

**Comment by Paititi** [comment]
Thanks, it's working now. Also how do I remove this module so I could recompile it with jack support? Not possible with "pip uninstall" command.

**Comment by belangeo** [comment]
No need to remove... Just recompile with --use-jack flag!

**Comment by Paititi** [comment]
I did that and it prints that Pyo built without Jack support.

**Comment by belangeo** [comment]
What command did you use to compile ?
Also, be sure that there is not an older version of pyo in another folder (for example, you compile and install for the system but a previous compilation was install in /usr/local/).

**Comment by Paititi** [comment]
> sudo python setup.py install --use-jack
I'm not sure that there is another pyo folder at all or maybe I don't understand something.

**Comment by belangeo** [comment]
For instance, on Debian, this command install in /usr/local/lib/python/dist-package/..., but

sudo python setup.py install --use-jack --install-layout=deb

will install in /usr/lib/python/dist-package/...

I Don't know how arch behave in this regard...

Two more questions:
1) the -dev package of jack is installed?
2) why don't you install pyo from the package manager (it's called python2-pyo).

**Comment by Paititi** [comment]
I checked and there is two folders (python 2.7 and 3.7) with modules in /usr/lib/ and nothing in /usr/local/lib/.
1. I guess not, not sure. I use jack2-dbus package.
2. It's in the user repository and I don't know who maintainer is. And I wouldn't be able to use this package with python3, right?

**Comment by belangeo** [comment]
Yes python2-pyo does not run with python3... I don't even use python2 myself anymore, I recommend you to use python 3.7.

I had some problems in the past with jack2-dbus and jack version (some incompatible changes) and made some tweak in setup.py to hardcode the right value. But I checked jack2-dbus ChangeLog and it seems that it now uses newer version of some functions. I made a little change to setup.py, can you update your sources and recompile ?

**Comment by Paititi** [comment]
Still the same message that pyo built without jack. Probably, I need to do complete uninstall of module.

**Comment by belangeo** [comment]
Maybe you need to remove the build directory before recompiling.

sudo rm -rf build && sudo python3 setup.py install --use-double --use-jack

**Comment by Paititi** [comment]
Nothing have changed. You know what, this isn't issue for me since I have successfully booted server and got sound. Thank you for you help and good luck with this project.
