### ISSUE TITLE
Making techno pattern using pyo

### ISSUE THREAD

**Issue by svatty89** [belangeo/pyo#136]
Hello. Not so fast as i would like to but i'm slowly make out how to work with pyo. I see very big opportunities to write music using it. But when i looked to documentation - i really felt that this idea would be not as pleasant as i thought due to the lack of knowledge about OOP. But. Just a few words, questions. Pardon me. Can you tell me, please, is there a way of making not a rhytm generator  no probabilitiy logic, no predefined static structure lile oscillator - as it looks alone without structure,  no other thing which are unhelpful for writing melodic base of the track. But the way of writing melody or close to melodic style example or method of doing so. 
  
  I really wounder, is there's a way of putting things together like that - is there in other words method of use of pyo which allowed me to write for example a melody, a bass line. Strictly and explicitly - i.g. like in sequensors and other stuff. Hold on please! I really understand the uniqueness of DSP stuff. But... Is there a way of, for example, creating oscilator and fix some frequences in it's places(e.g 440, 880, 660, 500 and so on) and then make a list of values(or other way programmingly put this signals  in it so that it would be melody or rhytmic structure)  exactly like that: that freq is playing on first bar of the tact , the next is on another bar and so on and ok. and Here it is - the melody. 

   Can i do something close to it maybe? Because when i looked documentation i realised that pyo doesn't support working with midi, this is in fact a big goal to implement this function i know it(usually   i wrote music via midi and with lists), but... I say it third time, pardon me.  This stuff (e.g. midi sequensors is boring and commercial), but pyo. I realy should know. 
  Can you be so kind and give me an example of melody line explicitly written(without random logic) for osc, and(or) example of drums or any other signals that forms pattern defined strictly as i mentioned above. 
   Maybe it's my fault - i don't understand well enough what cosine tables are, what are the triggers. I need a simple way of doing simple things. Want to do techno. Wx sequensor in pyo example allows to generate repeated signal. Drum example will help me to add my drum samples in the code and put them in correct order defined explicitly. all i need is the simple ostinato like theme('s) for osc synth, and some melody stuff too. But i couldn't get is there a way of doing this  - patterns. Because. I know there's is a lot to learn both theoretically and practically. It's not lazyness belive me(i spent about 5 hours last few days and earlier, any time i got a spare time), not stupiditness, i can code python, but i really don't get how to do this(maybe it's not the simpliest thing - DSP itself). documentation is amazing anyway. I wish i could understand all that endless possibilities of using pyo. But i need some working with structure first, because using this simple logic can give very powerfull results. I don't like daws and this piano roll things much. They are not able to give me this depth of sound processing.
 Sorry for bieng so long and overworldly. Love.

**Comment by belangeo** [comment]
Hi,
This is not really an issue, it should rather belong to the mailing list...
To answer the question, sure, you can write your sequence of events explicitly. Here is a quick example:

```
from pyo import *

s = Server().boot()

# An event is a tuple (pitch, velocity).
events = [(48, 100), (44, 70), (43, 60), (53, 100), (55, 70), (51, 55), (50, 40)]

# Rhythmic pattern.
rhythmic = [4, 2, 2, 4, 1.33, 1.33, 1.34]

# Duration, in seconds, of a value of 1 in the rhythmic pattern.
taptime = 0.2

# Amplitude envelope.
env = CosTable([(0,0), (64, 1), (512, 0.7), (4096, 0.7), (8192,0)])

# Sequence of triggers based on the rhythmic pattern.
seq = Seq(time=taptime, seq=rhythmic, poly=1, speed=1).play()

# Each trigger move forward in the event sequence.
freq = Iter(seq, [midiToHz(evt[0]) for evt in events])
amp = Iter(seq, [evt[1] / 127. for evt in events])
dur = Iter(seq, [tap * taptime for tap in rhythmic])

# Triggers the amplitude envelope.
shape = TrigEnv(seq, env, dur=dur, mul=amp)

# Stereo oscillator.
oscL = RCOsc(freq=freq, sharp=0.25, mul=shape).out()
oscR = RCOsc(freq=freq*1.001, sharp=0.25, mul=shape).out(1)

s.gui(locals())
```
Hope that help!

**Comment by svatty89** [comment]
Hello, Olivier!This is great absolutely! Don't get me wrong, it's not a um...don't know how to say it in english. I mean, it's not an act of impundence or what. I really would like to see example with drums. It's a pity that i don't know people in pyo community that can help with that. For that reason i write to you. Maybe it's a bit odd. But anyway, please forgive me if i take to much attension. It's for good sake i think. Because maybe this thing(dsp) along with math and music is the most significant in some way. When you have a little time, i would greatly appreciate answer to my second question.Hope it doesn't sound impundant.With best regards, svattty/04.12.2018, 05:02, "Olivier Bélanger" <notifications@github.com>:Hi,
This is not really an issue, it should rather belong to the mailing list...
To answer the question, sure, you can write your sequence of events explicitly. Here is a quick example:
from pyo import *

s = Server().boot()

# An event is a tuple (pitch, velocity).
events = [(48, 100), (44, 70), (43, 60), (53, 100), (55, 70), (51, 55), (50, 40)]

# Rhythmic pattern.
rhythmic = [4, 2, 2, 4, 1.33, 1.33, 1.34]

# Duration, in seconds, of a value of 1 in the rhythmic pattern.
taptime = 0.2

# Amplitude envelope.
env = CosTable([(0,0), (64, 1), (512, 0.7), (4096, 0.7), (8192,0)])

# Sequence of triggers based on the rhythmic pattern.
seq = Seq(time=taptime, seq=rhythmic, poly=1, speed=1).play()

# Each trigger move forward in the event sequence.
freq = Iter(seq, [midiToHz(evt[0]) for evt in events])
amp = Iter(seq, [evt[1] / 127. for evt in events])
dur = Iter(seq, [tap * taptime for tap in rhythmic])

# Triggers the amplitude envelope.
shape = TrigEnv(seq, env, dur=dur, mul=amp)

# Stereo oscillator.
oscL = RCOsc(freq=freq, sharp=0.25, mul=shape).out()
oscR = RCOsc(freq=freq*1.001, sharp=0.25, mul=shape).out(1)

s.gui(locals())

Hope that help!

**Comment by belangeo** [comment]
What is the second question?
