### ISSUE TITLE
an error in an example code of the doc

### ISSUE THREAD

**Issue by Fusyong** [belangeo/pyo#137]
an error in an example code of the doc:
```
[job.start() for job in jobs]
```
that should be:
```
[job.run() for job in jobs]
```
found here:
[How to improve performance of your pyo programs,](http://ajaxsoundstudio.com/pyodoc/perftips.html)
under the subtitle of "Use the subprocess or multiprocessing modules"

**Comment by belangeo** [comment]
User should never invoke the run() method of a process, it's the start() method that activate the process's activity. See:

[https://docs.python.org/3.4/library/multiprocessing.html?highlight=process#reference
](https://docs.python.org/3.4/library/multiprocessing.html?highlight=process#reference
)

**Comment by Fusyong** [comment]
Got it. 

But, how can I run them exactly? I get nothing running the scripts with `[job.start() for job in jobs]`,  but a sound with `[job.run() for job in jobs]`. My OS is Windows 7. 

Thanks.

**Comment by Fusyong** [comment]
Thanks for the details.

**Comment by rytrose** [comment]
Hi @belangeo, it seems like multiprocessing isn't working on macOS (Mojave, 10.14.2), either, as the server doesn't boot. Was multiprocessing working with previous versions of macOS, or is it not supported?

Here's a sample program I ran, which hangs after `print("booting server")`:

```
from pyo import *
import multiprocessing


def t():
    print("booting server")
    s = Server().boot()
    print("starting server")
    s.start()
    print("server started")
    
    snd = SndTable("test.wav")
    f = snd.getRate()
    p = Phasor(freq=f)
    sample = Pointer2(table=snd, index=p).out()


multiprocessing.Process(target=t).start()
```

**Comment by belangeo** [comment]
Hi @rytrose,

See this example, it works under MacOS:

[https://github.com/belangeo/pyo/blob/master/pyo/examples/18-multicore/01-processes-spawning.py](https://github.com/belangeo/pyo/blob/master/pyo/examples/18-multicore/01-processes-spawning.py)

**Comment by rytrose** [comment]
I tried that, with the same issue, all processes hang indefinitely at [`self.server.boot().start()`](https://github.com/belangeo/pyo/blob/master/pyo/examples/18-multicore/01-processes-spawning.py#L30).

**Comment by belangeo** [comment]
Did you remove audio="jack" ? Also, be sure that self.daemon is True.

**Comment by rytrose** [comment]
Yes and yes! `"portaudio"` and `self.daemon = True`. Is it perhaps a Mojave issue? I've had permissions errors before since Mojave locked a lot down, including audio inputs.

**Comment by belangeo** [comment]
Don't know... I don't have Mojave myself... I will try with High Sierra in a few days.

**Comment by rytrose** [comment]
Okay, thanks for your help! pyo is really awesome, I've very much enjoyed using it :)
