### ISSUE TITLE
E-Pyo doesn't see Pyo

### ISSUE THREAD

**Issue by MaksGrabowy** [belangeo/pyo#140]
When i try to launch an example it shows me this

`=== Output log of process "01-complex-oscs.py", launched: "30 Mar 2019 15:17:16" ===
Traceback (most recent call last):
  File "01-complex-oscs.py", line 24, in <module>
    from pyo import *
ModuleNotFoundError: No module named 'pyo'
`

The same thing happens in Spyder, in which i want to code. I am using Windows 10 and python 3.7

**Comment by belangeo** [comment]
There is no installer of pyo for python 3.7 at the moment. Next release will install with pip and will work for 3.7. You need to use python 3.6 for now.
