### ISSUE TITLE
pyo midi on OS X

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#142]
I am trying to get midi working with Pyo on OS X. So far no luck. The samples I tried gave me a midi note in once, then nothing.
The pm_list_devices() gives me a command prompt (>)
BTW, I cannot use wxPython. I installed it for Python 3.5 (Anaconda) but get this error:
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

Richard

**Comment by belangeo** [comment]
Not sure what you mean with "The samples I tried ...". pm_list_devices() only print to the output the available MIDI devices at the moment you launch your script. If you plug a keyboard, then run this script, it should work as is:

```
from pyo import *

s = Server()
s.setMidiInputDevice(99) # open all MIDI devices.
s.boot()
s.start()

notes = Notein(scale=1)
amp = Port(notes["velocity"], 0.005, 1)
synth = SuperSaw(freq=notes["pitch"], mul=amp).mix().mix(2).out()

s.gui(locals())
```

**Comment by zappfinger** [comment]
Ok, I more or less got it going now, but only for Python 2.7. On Python3.5 (Anaconda) I could not even run pyo after I installed wxPython. So I uninstalled that first. Then Pyo worked, but with midi I got the intermittent behaviour I described. Then I installed Pyo also for Python2.7 and with the following command it seemed ok: /usr/local/bin/pythonw midiTest.py

**Comment by zappfinger** [comment]
One succes story: I did manage to compile Pyo on my Raspberry Pi...

Richard

**Comment by belangeo** [comment]
Yes, anaconda and wxpython never been a good match! I never used anaconda myself as it is so easy to install any wanted (and no more!) modules with pip and a python.org install. For the midi with pyo on python3, I just don't understand the problem. Can you show the script which is not working correctly?

**Comment by zappfinger** [comment]
I tried now to install python3.7.3 on OS X next to anaconda. I made an alias for python to point to python3. Then I ran your installer for OS X. It installed Ok, but opening Python3 and importing pyo gave me 'ModuleNotFoundError: No module named 'pyo'. So I guess it installed it not for Python 3.7, maybe for my older Python3.5 (anaconda).  Where is it installed? Can I force the installer to use a certain version of Python?

**Comment by belangeo** [comment]
Actually, there is no binary installer of pyo for python 3.7 on ajaxsoundstudio, only 2.7, 3.5 and 3.6. So I guess you have pyo files in /Library/Frameworks/Python.framework/Versions/x.x/lib/... Either you use one of these versions or you can install pyo for 3.7 with pip (still working on wheels but MacOS ones are ready):

```
sudo` python3.7 -m pip install -i https://test.pypi.org/simple/ pyo
```
As of 0.9.2, E-Pyo.app does not longer exist. It's a now simple commandline script installed next to pyo. You can start the editor with:

```
epyo
```

**Comment by zappfinger** [comment]
I tried that, but import pyo gives me:
from .._pyo import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyo/_pyo.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/pyodeps/liblo.7.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyo/_pyo.cpython-37m-darwin.so
  Reason: Incompatible library version: _pyo.cpython-37m-darwin.so requires version 11.0.0 or later, but liblo.7.dylib provides version 10.0.0

**Comment by belangeo** [comment]
Oups... My fault. I'll have time tonight to fix it!

**Comment by zappfinger** [comment]
Would be great!

**Comment by belangeo** [comment]
I uploaded a new version to test.pypi.org (MacOS 10.9+ only for now, I'll upload windows wheels asap).

```
sudo python3.7 -m pip install -U -i https://test.pypi.org/simple/ pyo==0.9.3
```
Maybe you shoud double-check that there is no `pyodeps` folder in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ or /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyo. That was the first test to bundle pyo's dependencies into a wheel but this folder should no longer be there.

Let me know if it works for you.

**Comment by zappfinger** [comment]
Yes this works! Thanks!

**Comment by rytrose** [comment]
@zappfinger were there any gotchas or difficulties building for Raspberry Pi? Very interested in doing that myself, curious if there is anything I should look out for :)

**Comment by zappfinger** [comment]
rytrose, no problems encountered, I just followed the steps....

**Comment by rytrose** [comment]
Okay, great! Sometimes there can be tricky things on Raspberry Pi and I hadn't seen anyone talk about doing it before so I was just curious about your experience. Thanks!

**Comment by belangeo** [comment]
@rytrose install the dependencies, clone pyo sources and compile. It should be straightforward... You can use compiling for debian as a guide:

[http://ajaxsoundstudio.com/pyodoc/compiling.html#debian-ubuntu-apt-get](http://ajaxsoundstudio.com/pyodoc/compiling.html#debian-ubuntu-apt-get)

You probably don't want to install wxpython (python-wxgtk3) on the rPi...

**Comment by rytrose** [comment]
@belangeo, thanks! Yep, didn't think that would be a good idea. :)
