### ISSUE TITLE
Pyo on windows

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#143]
I installed pyo on Windows 10, but it acts strange.
E-Pyo starts up, but there is also an e-Pyo black screen with the text: "erasing preferences"
When I run an example in the normal e-Pyo window, nothing happens. No sound, and I do not see any server windows appear (to start/stop)..

Richard

**Comment by belangeo** [comment]
The black screen is just a command prompt attached to the GUI process (E-Pyo text editor). It is the same as starting epyo from the command line on linux or MacOS. It's a little bit anoying but there is nothing to worry about, if something goes wrong with the app (E-Pyo, not the running script), output log will be printed there.

In the E-Pyo editor, if you open an example from the "Pyo Examples" menu and run it, what happens?

Which version of python are you running on this computer?

**Comment by zappfinger** [comment]
Python 2.7.14. When I run an example only the text appears that I do not
have wxPython installed. No server window pops up, no sound is heard, even
if I add a line : s.start()

Richard

Op vr 12 apr. 2019 om 18:03 schreef Olivier Bélanger <
notifications@github.com>:

**Comment by belangeo** [comment]
Not sure what goes wrong here. Maybe a screenshot of the windows will help...

Any reason to still use python 2.7 ? It's support ends on January 1, 2020. If you install python 3.7, you can then install both pyo (also available for python 64-bit) and wxpython with pip:

```
py -3.7 -m pip install -i https://test.pypi.org/simple/ pyo
py -3.7 -m pip install -U wxPython
```

**Comment by zappfinger** [comment]
I could not pip install pyo like that, because it said requirement already
satisfied. So I tried pip uninstall, but that complained:
Cannot uninstall 'pyo'. It is a distutils installed project and thus we
cannot accurately determine which files belong to it which would lead to
only a partial uninstall.



Op za 13 apr. 2019 om 13:23 schreef Olivier Bélanger <
notifications@github.com>:

**Comment by zappfinger** [comment]
Success!: I had to use reinstall flag as well (-I), so:
py -3.7 -m pip install -I -i https://test.pypi.org/simple/ pyo

Op za 13 apr. 2019 om 13:59 schreef Richard van Bemmelen <
zappfinger@gmail.com>:

**Comment by zappfinger** [comment]
But still no sound. I noticed the following settings:
sr=44100, nchnls=2, buffersize=256, duplex=1, audio="portaudio",
jackname="pyo"
That does not look Windowish.. What should I use fpr Windows?

Op za 13 apr. 2019 om 14:06 schreef Richard van Bemmelen <
zappfinger@gmail.com>:

**Comment by zappfinger** [comment]
I used your test code, but I think it is wrong. It said I had to use
duplex=1, but that did not work. I had to use duplex=0:

this worked for me:
s=Server(buffersize=1024, duplex=0, winhost='asio')

Richard


Op za 13 apr. 2019 om 14:12 schreef Richard van Bemmelen <
zappfinger@gmail.com>:

**Comment by belangeo** [comment]
These values are only for the background server, which is not used when you "run" a script. However, the jackname argument is just ignored on windows. Portaudio is the only available audio backend.
 
How did you run your script? If from Epyo, you have to start the editor from the command promt (or the "cmd" window) with the command `epyo`, not from the .exe that is probably still on your Desktop (and surely belong to another python version!).

To do a clean uninstall on Windows, run the uninstaller that comes with pyo to remove all its components. It is located in the python root directory (ex.: C:\Python27) and named 'unins000.exe'.

**Comment by belangeo** [comment]
If you have to set `duplex=0`, that means you don't have any configured input for that driver. `duplex=1` means you want to connect the server to both inputs and outputs.
