### ISSUE TITLE
instance of dummy class

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#144]
In my PySimpleGUI event loop I try to get midi events like this:
while True:
    event, value = window.Read(timeout=20)
    #print(event)
    if server.getIsStarted():
        notes = pyo.Notein(scale=1)
        amp = notes["velocity"]
        pit = notes["pitch"]
        print(pit)

But  the print only outputs:
< Instance of Dummy class >
< Instance of Dummy class >
< Instance of Dummy class >

What is wrong here?

**Comment by belangeo** [comment]
You can't do something like:

```
while True:
    if server.getIsStarted():
        notes = pyo.Notein(scale=1)
```
Because it creates a new Notein object every time the loop is executed.
Notein["velocity"] and Notein["pitch"] returns audio stream objects (Dummy), if you want float values, you can use the get() method of the PyoObject.

It should be something like:

```
notes = pyo.Notein(scale=1)
while True:
    if server.getIsStarted():
        amp = note["velocity"]
        pit = note["pitch"]
        # amp and pit are audio objects (Dummy) holding signals containing
        # current amplitudes and frequencies of the voices managed by the Notein.
        # To retrieve values as float, you can use .get() method.
        amplitudes = amp.get(True)
        frequencies = pit.get(True)
```

**Comment by zappfinger** [comment]
Why is this not described here in the docs about notein? http://ajaxsoundstudio.com/pyodoc/api/classes/midi.html#notein
From the example it seems that this is valid code:
b = Sine(freq=notes['pitch'], mul=p).out()

thus suggesting that notes['pitch'] would contain the frequency?

**Comment by belangeo** [comment]
> Why is this not described here in the docs about notein? 

It is... From the doc:

> Note: Pitch and velocity are two separated set of streams. The user should call :
> Notein[‘pitch’] to retrieve pitch streams.
> Notein[‘velocity’] to retrieve velocity streams.
> Velocity is automatically scaled between 0 and 1.

The fact that Notein is a class derived from the PyoObject class implies that it generates an audio signal, and not a number in the sense python understand them (int, float).

> From the example it seems that this is valid code:
> b = Sine(freq=notes['pitch'], mul=p).out()
> thus suggesting that notes['pitch'] would contain the frequency?

True, but the frequencies as audio signals. The `freq` argument of the Sine class accepts both float or PyoObject (and implicitly a list of floats or a list of PyoObjects) as control value.

Then, if you want to print the current value of an audio stream, you can't use python's print function (which only prints the object's class name) but the pyo's Print object.

http://ajaxsoundstudio.com/pyodoc/api/classes/utils.html?highlight=print#pyo.Print

The subtlety here is that python has no notion of time but sound is nothing but evolution of the signal over time! PyoObjects do work as long as the script runs but python's calls are executed only once.
