### ISSUE TITLE
Improving latency for audio effect

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#146]
I am trying some audio effects on OS X, but the latency is not so good. I tried several buffer sizes, but that hardly makes a difference. What can I do to reduce latency?

Example code:
```
import pyo

s = pyo.Server(buffersize=128, nchnls=1).boot()
s.start()

# chorus
#a = pyo.Input(chnl=0)
#chorus = pyo.Chorus(a, depth=.5, feedback=0.5, bal=0.5).out()

# delay
a = pyo.Input(chnl=0).out()
delay = pyo.Delay(a, delay=.5, feedback=.5).out()

s.gui()
```

**Comment by belangeo** [comment]
What is your soundcard? On which system? With a buffersize of 128, you should not really feel the latency at all (~3 ms @ sr = 44100).

**Comment by zappfinger** [comment]
This is on OS X 10.13.14
Soundcard is a Scarlett 2i2 USB device....
AUDIO devices:
0: IN, name: Built-in Microphone, host api index: 0, default sr: 44100 Hz, latency: 0.002971 s
1: OUT, name: Built-in Output, host api index: 0, default sr: 44100 Hz, latency: 0.004626 s
2: IN, name: Scarlett 2i2 USB, host api index: 0, default sr: 44100 Hz, latency: 0.010000 s
2: OUT, name: Scarlett 2i2 USB, host api index: 0, default sr: 44100 Hz, latency: 0.003515 s

Default input device: 2
Default output device: 2

This should indeed have a latency of about 10 ms....

**Comment by belangeo** [comment]
How much latency do you get? Do you have a way to verify if the buffer size of your soundcard is effectively set to 128?

**Comment by zappfinger** [comment]
The following settings seem to have solved it:
s = pyo.Server(duplex=1, audio='coreaudio', buffersize=512, nchnls=1).boot()

I think coreaudio was not on by default...

**Comment by belangeo** [comment]
Oh, I'm surprised that the coreaudio support is better than portaudio, I wrote this code under OSX 10.5 - 10.6. I was thinking to remove it completely, but maybe it's time to update it to the latest API!

**Comment by belangeo** [comment]
Coreaudio update is added to the TODO list. Closing this issue.
