### ISSUE TITLE
Using PyoGUI objects with PySimpleGUI

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#147]
I wonder if it is possible to use objects like Scope and Spectrum in PySimpleGUI?

**Comment by belangeo** [comment]
Don't think so... Pyo GUI objects are written with wxpython and PySimpleGUI with tkinter and you can't run two GUI frameworks at the same time. Both want to take control of the event loop.

**Comment by zappfinger** [comment]
Ok, but there is also a wx version of PySimpleGUI. So I installed that but got this error:
 File "/Users/richard/PycharmProjects/pyoTest/audioInChorus.py", line 63, in <module>
    event, value = window.Read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySimpleGUIWx/PySimpleGUIWx.py", line 3209, in Read
    self.Show()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySimpleGUIWx/PySimpleGUIWx.py", line 3117, in Show
    StartupTK(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PySimpleGUIWx/PySimpleGUIWx.py", line 5328, in StartupTK
    panel.SetTransparent(.5)
wx._core.wxAssertionError: C++ assertion "(style != wxBG_STYLE_TRANSPARENT) || !GetHandle()" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/wincmn.cpp(1637) in SetBackgroundStyle(): wxBG_STYLE_TRANSPARENT style can only be set before Create()-ing the window.

I will ask this on their forum...

**Comment by belangeo** [comment]
After a few changes to PySimpleGuiWx.py to make it work on my linux box with python 3.5, I got it working. 

There is two things to consider: 

1) The wx.App object must be created before instantiating a PyoGuiScope object. What is a little bit weird with PySimpleGuiWx is that this object is not created in the Layout method of the Window object but in the Read() method, which is called only when the GUI send an event.

2) PyoGui objects are panels, not frames... We have to put them in a frame to be able to show them on screen (when used inside pyo, the frame is already built).

This works (but the sliders don't show up on my computer):

```
import pyo, math, wx
import PySimpleGUIWx as sg

class ScopeFrame(wx.Frame):
    def __init__(self, parent, title, analyzer, pos=(50, 50), size=(600, 300)):
        wx.Frame.__init__(self, parent, -1, title, pos, size)
        self.analyzer = analyzer
        self.panel = wx.Panel(self)
        sizer = wx.BoxSizer(wx.VERTICAL)
        self.scope = pyo.PyoGuiScope(parent=self.panel)
        self.scope.setAnalyzer(self.analyzer)
        sizer.Add(self.scope, 1, wx.ALL | wx.EXPAND, 5)
        self.panel.SetSizerAndFit(sizer)
        self.Show()

s = pyo.Server(duplex=1, audio='coreaudio', buffersize=256, nchnls=2).boot()

def updateMeter(*args):
    "Update the vumeter display."
    meter.UpdateBar(100 + 20 * math.log10(args[0]))

a = pyo.Input(chnl=0)

# Apply a portamento to the values coming from the interface.
disto = pyo.SigTo(value=.5, time=0.02, init=.5)
slopev = pyo.SigTo(value=.5, time=0.02, init=.5)

dist = pyo.Disto(a, drive=disto, slope=slopev, mul=.15)

sc = pyo.Scope(dist)
rms = pyo.RMS(dist, function=updateMeter)

# GUI
layout = [[sg.Checkbox('Start Audio', auto_size_text=True, change_submits=True)],
          [sg.Slider(range=(0, 100), orientation='h', default_value=25,
           tooltip="Distortion", change_submits=True)],
          [sg.Slider(range=(0, 100), orientation='h', default_value=20,
           tooltip="Slope", change_submits=True)],
          [sg.ProgressBar(100, orientation='h', size=(20, 20), key='meter')],
          [sg.Quit()]]
window = sg.Window('Pyo with PySimpleGUI').Layout(layout)

meter = window.FindElement('meter')

scope_shown = False
while True:
    event, value = window.Read()
    if not scope_shown:
        scFrame = ScopeFrame(None, "Oscilloscope", sc)
        scope_shown = True
    print(event, value)
    if event == 0:          # Handle the audio server
        if value[0]:
            s.start()
        else:
            s.stop()
    elif event == 1:        # Change dist
        disto.value = value[1] / 100.
    elif event == 2:        # Change slope
        slopev.value = value[2] / 100.
    elif event =='Quit' or event is None:
        if s.getIsStarted():
            s.stop()
        scFrame.Destroy()
        window.Close()
        break

```

**Comment by belangeo** [comment]
Oh, better... You can call Show() yourself on the Window object. Instead of waiting for a Read() call to show the Scope window, you can do:

```
window = sg.Window('Pyo with PySimpleGUI').Layout(layout)
window.Show(non_blocking=True)

scFrame = ScopeFrame(None, "Oscilloscope", sc)

```

**Comment by zappfinger** [comment]
Great job! Thanks!

Richard

Op do 2 mei 2019 om 02:39 schreef Olivier Bélanger <notifications@github.com
