### ISSUE TITLE
OSC and polyphony

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#151]
I am working on a midifile to OSC converter and use a simple server that plays a sine wave:
```
from pyo import Server, OscDataReceive, OscReceive, Sine
import time
s = Server().boot().start()
a = OscReceive(port=8000, address=['/pitch', '/amp'])
b = Sine(freq=a['/pitch'], mul=a['/amp']).mix(2).out()
while 1:
	time.sleep(.0001)
```
There seems to be a problem when notes come in at the same instant (a chord). Only one note is heard. My client program reads the file moonlight_sonata.mid, parses it and sends the data over OSC. With OSC_Data_Monitor I can see all the notes coming in...

I also tried it with OscListReceive, like your example in the docs, but this crashes Python...
```
a = OscListReceive(port=8000, address=['/pitch', '/amp'])
b = Sine(freq=a['/pitch'], mul=a['/amp']).mix(2).out()
```

Richard

**Comment by belangeo** [comment]
OscReceive, as it is instantiate only manage two audio streams, one for pitch and one for velocity, so it can only handle one note at a time. OscListReceive expects list of floats as input, the sender must be configure the right way. 
In this case, I'll go with OscDataReceive to be able to manage discrete midi events. Something like this:

```
from mido import MidiFile
from pyo import *

s = Server().boot().start()

# Receive OSC event and route them, as midi, to the server.
def OSC_receive(address, *args):
    if address == "/midievent":
        s.addMidiEvent(args[0], args[1], args[2])
receiver = OscDataReceive(9990, "/midievent", OSC_receive)

# Midi synth player.
midi = Notein()
amp = MidiAdsr(midi['velocity'])
pitch = MToF(midi['pitch'])
wave = SquareTable()
osc = Osc(wave, freq=pitch, mul=amp)
verb = Freeverb(osc, bal=0.25).out()

mid = MidiFile('/path/to/midifile.mid')

# Set-up the Osc sender to send three integers per message.
sender = OscDataSend("iii", 9990, "/midievent", host="127.0.0.1")

# For each midi event, build a message (always a list) and send it.
for message in mid.play():
    msg = [*message.bytes()]
    sender.send(msg) # list of three integers.
```

**Comment by belangeo** [comment]
Closing as not an issue.
