### ISSUE TITLE
GM percussion parsing

### ISSUE THREAD

**Issue by zappfinger** [belangeo/pyo#153]
How would I route midi note numbers to tables with stored wave forms? E.g. in a General Midi file for drums, key number 34 could be Bass drum, 36 could be snare, etc.

Richard

**Comment by belangeo** [comment]
One table per key, something like this:

```
t1 = SndTable("kick")
t2 = SndTable("other")
t3 = SndTable("snare")
# t4 ...

# This example assumes one full octave of loaded sounds
tables = [t1, t2, t3]

notes = Notein(poly=12, first=34, last=45)
reader = TrigEnv(notes["trigon"], tables, dur=1).out()
```

If you use programmatically discrete events, a dictionary could be used to map note number to the corresponding table.

**Comment by zappfinger** [comment]
And for the velocity, can I use this?
```
reader = TrigEnv(notes["trigon"], tables, dur=1, mul=notes["velocity"]).out()
```

**Comment by belangeo** [comment]
Yes, this should work!

You'll probably want to set the `dur` argument to the duration of each table (to avoid transposition):

```
dur = [table.getDur() for table in tables]
reader = TrigEnv(notes["trigon"], tables, dur=dur, mul=notes["velocity"]).out()
```

**Comment by belangeo** [comment]
Closing as not an issue.
