### ISSUE TITLE
Getting SndTable to read mp3/m4a, or loading arbitrary audio data

### ISSUE THREAD

**Issue by radkoff** [belangeo/pyo#154]
Hey, thanks for open-sourcing pyo!

I'm trying to load portions of common audio file types into memory, namely mp3 and m4a, but I keep getting:
```
  File "/Users/evan/anaconda3/lib/python3.6/site-packages/pyo-0.9.7-py3.6-macosx-10.7-x86_64.egg/pyo/lib/players.py", line 110, in __init__
    _snd_size, _dur, _snd_sr, _snd_chnls, _format, _type = sndinfo(path[0])
TypeError: 'NoneType' object is not iterable
```

I've tried both SndTable and SfPlayer, with dozens of different files. The only formats I can get working are aiff and wav. I thought coreaudio might be the issue, so I rebuilt pyo with Jack, but that doesn't work either. I'm on macOS 10.13.6, using the most recent code built from source.

What does pyo use to load audio into memory? Usually I use librosa, and it can handle pretty much any format. Is there a way to take arbitrary audio content (as a numpy array) and load it into a PyoTableObject or similar?

**Comment by belangeo** [comment]
Pyo uses libsndfile for reading/writing audio file from/to disk. You can see all formats pyo can handle here:

[http://ajaxsoundstudio.com/pyodoc/api/functions/sndfile.html?highlight=ogg#savefile](http://ajaxsoundstudio.com/pyodoc/api/functions/sndfile.html?highlight=ogg#savefile)

It is very easy to load the content of an array into a table, try something like this:

`t = DataTable(size=yourarray.size, init=yourarray.tolist())`

DataTable also has a `chnls` argument if you want to use multi-dimensional array.

**Comment by radkoff** [comment]
Thanks, I got mono audio playing! Though, I'm still getting this error when I try stereo:
```
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

  File "/Users/evan/Desktop/Audio analysis/Code/autoaudio/src/gen/pyotest2.py", line 18, in <module>
    t = pyo.DataTable(size=audio.size, init=audio.tolist(), chnls=2)
  File "/Users/evan/anaconda3/lib/python3.6/site-packages/pyo-0.9.7-py3.6-macosx-10.7-x86_64.egg/pyo/lib/tables.py", line 2107, in __init__
    self._base_objs = [DataTable_base(size, wrap(init,i)) for i in range(chnls)]
  File "/Users/evan/anaconda3/lib/python3.6/site-packages/pyo-0.9.7-py3.6-macosx-10.7-x86_64.egg/pyo/lib/tables.py", line 2107, in <listcomp>
    self._base_objs = [DataTable_base(size, wrap(init,i)) for i in range(chnls)]
SystemError: <class '_pyo.DataTable_base'> returned a result with an error set
```

`audio.shape` is (2, 5002116), with a dtype of float32. I also tried passing in the transpose, `audio.T.tolist()`

**Comment by belangeo** [comment]
My guess is the size (`audio.size`) is wrong as it returns the sum of the two arrays. This works: 

```
import numpy
from pyo import *

s = Server().boot()
sr = int(s.getSamplingRate())

a = numpy.array((numpy.random.random(sr) - 0.5, numpy.random.random(sr) - 0.5))

t = DataTable(a.shape[1], chnls=a.shape[0], init=a.tolist())

o = Osc(t, freq=1).out()
sc = Scope(o)

s.gui(locals())
```

**Comment by radkoff** [comment]
That worked great :)
