### ISSUE TITLE
Pyo GUI windows too small OS X

### ISSUE THREAD

**Issue by daanklijn** [belangeo/pyo#163]
Running on MacOS Mojave 10.14.6. Any idea how to resize all pyo GUI windows?
![image](https://user-images.githubusercontent.com/27863547/66783789-f7d83880-eed8-11e9-9bf4-9b6444f67b69.png)

**Comment by belangeo** [comment]
Thanks for reporting. Fixed for the next release. BTW, you should really install wxPython (`pip install wxPython`), pyo try to use this gui toolkit first and if it is not installed, it falls back to a minimal tkinter implementation. You'll have access to more GUI tools if you install wxPython!

**Comment by daanklijn** [comment]
That works like a charm. Really appreciate the module, thanks again!

**Comment by jacksonmgoode** [comment]
Hi, I wanted to follow this thread up by using the image to ask if the colors in the GUI are correct. I get a very white, low-contrast representation like the one in the image and was wondering if that was normal (both on the ktinker and wx versions).

**Comment by belangeo** [comment]
The colors in the image above looks like the default TK implementation... Are you using the system's dark mode?

**Comment by jacksonmgoode** [comment]
> The colors in the image above looks like the default TK implementation... Are you using the system's dark mode?

Ah, yes I am. Does that mess with the colors?

**Comment by belangeo** [comment]
Maybe... Try without dark mode and if everything looks fine, then I'll have to do something to handle it within pyo (or find a way to make wxpython handle it itself). You can open an issue about it!
