### ISSUE TITLE
wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by timpauli** [belangeo/pyo#164]
Hi,

I am on Ubuntu 19.10 and removed the package I installed before via `apt-get`, and installed then via `pip3 install --no-cache-dir pyo`. When I run `from pyo import *` I get
```
File "/home/user/.local/lib/python3.7/site-packages/pyo/__init__.py", line 25, in <module> 
   from . import _linux_wheel_fix_symlinks
File "/home/user/.local/lib/python3.7/site-packages/pyo/_linux_wheel_fix_symlinks.py", line 88, in <module>
   libasound = ctypes.CDLL(libasound, mode=ctypes.RTLD_GLOBAL)
File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
   self._handle = _dlopen(self._name, mode)
OSError: /home/user/.pyo/3.7_64/libs/libasound-fb332ab3.so.2.0.0: wrong ELF class: ELFCLASS32
```
What could be the Problem?

Thank you very much.
Great Project.
Tim

**Comment by belangeo** [comment]
Hi,

libasound-fb332ab3.so.2.0.0 is a symbolic link to the libasound library
installed on your system. For some reason, you have libasound 32-bit
install but pyo is now only compile for 64-bit. My guess is that you have
installed a 32-bit libasound in the past for some reason (playing with wine
for example) and it is still lying around! Make sure that only the 64-bit
libasound is install, delete the folder /home/your_user/.pyo and try to
import pyo again, thatshould do it!

Olivier

**Comment by timpauli** [comment]
nice
`sudo apt remove libasound2:i386 libasound2-plugins:i386` worked.
thx for the quick response.

**Comment by krysopath** [comment]
I have the same issue just that I cant remove my libraries on my system as they are needed elsewhere.

Would be nice to fix provide a fix. Maybe LD_PRELOAD can help?

**Comment by dvdn** [comment]
For those who are landing here, you shouldn't have to compromise a working application to solve the problem of another. For example if you use Wine (that uses some 32-bits libs) on a x64 Linux Ubuntu.

Here's an easy fix > simply **edit problematic symlinks to expected x64 files** !

From my error :

`OSError: /home/zaphod/.pyo/3.10_64/libs/libasound-c32f6dbc.so.2.0.0: wrong ELF class: ELFCLASS32`

Check problematic symlinks, libasound & libjack in my case :

```
➜ ls -la /home/zaphod/.pyo/3.10_64/libs/                    
...
libasound-c32f6dbc.so.2.0.0 -> /usr/lib/i386-linux-gnu/libasound.so.2.0.0
libjack-bfec9b58.so.0.1.0 -> /usr/lib/i386-linux-gnu/libjack.so.0
...
```

Check path of your x64 files :


```
➜ dpkg -L libasound2
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
/usr/share
...

➜ dpkg -L libjack-jackd2-0:amd64 
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
...
/usr/lib/x86_64-linux-gnu/libjack.so.0
...
```

Then just modify symlinks to valid x64 files,
go into your personal .pyo libs directory

`➜ cd /home/zaphod/.pyo/3.10_64/libs/
`

then 

```
➜ sudo ln -sf /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0 libasound-c32f6dbc.so.2.0.0 
➜ sudo ln -sf /usr/lib/x86_64-linux-gnu/libjack.so.0 libjack-bfec9b58.so.0.1.0 
```

Et voilà :smile:
