### ISSUE TITLE
Add a way to defer Events

### ISSUE THREAD

**Issue by DataTriny** [belangeo/pyo#167]
Hi,

Given this piece of code:

```
class Kick(EventInstrument):
	def __init__(self, **args):
		EventInstrument.__init__(self, **args)
		self.f = Fader(fadein = 0.01, fadeout = 0.3, dur = 0.5)
		self.s = Sine(freq = self.freq, mul = self.f.play()).mix(2).out()

class Snare(EventInstrument):
	def __init__(self, **args):
		EventInstrument.__init__(self, **args)
		self.f = Fader(fadein = 0.01, fadeout = 0.3, dur = 0.5, mul = 0.7)
		self.n = PinkNoise(mul = self.f.play()).mix(2).out()

s = Server().boot().start()
kicks = Events(instr = Kick, degree = 4, beat = 1)
snares = Events(instr = Snare, degree = 4, beat = 2)
kicks.play()
snares.play()
```

We get the following pattern:

| 1 | 2 | 3 | 4 |
|---|---|---|---|
| Kick | Kick | Kick | Kick |
| Snare | | Snare | |

However, if I want:

| 1 | 2 | 3 | 4 |
|---|---|---|---|
| Kick | Kick | Kick | Kick |
| | Snare | | Snare |

I would like to be able to describe my `Events` like so:

```
kicks = Events(instr = Kick, degree = 4, beat = 1)
snares = Events(instr = Snare, degree = 4, beat = 2, beatOffset = 1)
```

This would mean: let one beat pass before starting. It could internally store the time computation in `offset` (which would represent the time in second before starting to play).

I can submit a PR if this feature make sense.

**Comment by belangeo** [comment]
I would prefer not to add other arguments that are only used at initialization. Delaying the computation of an audio process is something already implemented in the PyoObject (`dur` and `delay` argument of `play` and `out` methods). I've just added the same arguments to Events.play ( 2684565 ). You have to do the calculation to seconds yourself, but this keep the set of built-in arguments as small as possible. 

Try it and tell me if it fulfils your needs!

**Comment by DataTriny** [comment]
Hello @belangeo,
I didn't think about this option!
I just tried passing delay to `Events.play` and it worked perfectly.
Maybe we could add a new `beatToDur(bpm, beat)` utility function then?

**Comment by belangeo** [comment]
Done in ce75930 !

**Comment by DataTriny** [comment]
Thanks for the quick reply! The new function works like a charm!
Closing this issue then.
