### ISSUE TITLE
How would i control ADSR or LFO waveform type with midictl?

### ISSUE THREAD

**Issue by Glutch** [belangeo/pyo#172]
pyo isnt too happy when i try to set the lfo type to a midictrl. And i cant seem to figure out how to grab the value from it either. Any help greatly appreciated!

**Comment by Glutch** [comment]
I found [this example](https://groups.google.com/forum/#!searchin/pyo-discuss/midictl%7Csort:date/pyo-discuss/DDIndBCdvUI/Q9S9sO0YCQAJ) and got it working!

However i cant seem to get it to work when using the mix. Can you show an example of waveform midictl switching using this example?

http://ajaxsoundstudio.com/pyodoc/examples/16-midi/05-control-change.html

**Comment by belangeo** [comment]
Yes, LFO.type only accepts integer (Adsr arguments are float only), not audio signal. You can setup a callback that grab the midi controller value when it changes, convert the signal to an integer and set the waveform type of LFO.

```
from pyo import *

s = Server()
s.setMidiInputDevice(99)
s.boot()

a = LFO(200, mul=0.3).out()

def set_new_type():
    val = int(m.get())
    a.type = val

m = Midictl(0, minscale=0, maxscale=8)
tf = TrigFunc(Change(Round(m)), set_new_type)

s.gui(locals())

```

**Comment by belangeo** [comment]
Yes, the mix() method returns a Mix object, which is not the LFO you want to control. All you have to do is to put the mix call afterwards so `self.osc1` and `self.osc2` are really references to LFO objects.
```
        self.osc1 = LFO(self.pit, sharp=0.5, type=2, mul=self.amp)
        self.osc2 = LFO(self.pit*0.997, sharp=0.5, type=2, mul=self.amp).

        # Stereo mix.
        self.mix = Mix([self.osc1.mix(1), self.osc2.mix(1)], voices=2)

```

**Comment by Glutch** [comment]
thank you a lot! works wonderfully. pyo is awesome :)

do you have any tips to get a nice delay for arpeggios? i've tried them all with different parameters but they all sound weird and the initial "attack" gets delayed too

**Comment by belangeo** [comment]
Not sure to understand what you are trying to do...

**Comment by belangeo** [comment]
Closing as the initial problem is fixed.
