### ISSUE TITLE
The server is not booting

### ISSUE THREAD

**Issue by bakirillov** [belangeo/pyo#174]
Hello!

s = Server().boot() fails with the following error:
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Pyo warning: Portaudio output device `HDA Intel PCH: ALC3266 Analog (hw:0,0)` has fewer channels (0) than requested (2).
Portaudio error in Pa_OpenStream: Invalid number of channels
Pyo error: From portaudio, Invalid number of channels
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
Pyo error: 
Server not booted.

What am I doing wrong?

**Comment by belangeo** [comment]
> Pyo warning: Portaudio output device HDA Intel PCH: ALC3266 Analog (hw:0,0) has fewer channels (0) than requested (2).

This tells that portaudio doesn't find any output channels on your device... Either there is really no physical output, in which case pyo is rather useless or some other application already use the audio device...

**Comment by lodenrogue** [comment]
So how do we fix this?

**Comment by belangeo** [comment]
You make sure that no other application has control over the output audio driver, or you use a multi-client driver like jack. I'm on Debian and whenever I want to do something with sound, I use jack.
