### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by rsp4jack** [belangeo/pyo#175]
Server can't boot and crash.
s = Server().boot()
Process finished with exit code -1073741819 (0xC0000005)

**Comment by chninkel** [comment]
Same issue
python 3.7 x64
pyo cp37 amd64
windows 10

**Comment by edouin** [comment]
Same.
python 3.7 x64
windows 10

**Comment by Creepercdn** [comment]
i use
Anaconda3 2019.10
windows 10

**Comment by Creepercdn** [comment]
windows 10 python3.8.2 also can't work

**Comment by Creepercdn** [comment]
x64

**Comment by Steven-Rowell** [comment]
@Creepercdn - I was having this same issue in windows but not in linux. 

I saw this thread tonight - https://github.com/belangeo/pyo/issues/159

I'm not sure _why_ its happening, but I was able to work my way into a fix. 

Try this:

First. Disconnect any unneeded devices from your computer. In my case my Midi keyboard was causing issues 😕. Next, run:

```
from pyo import *
pa_list_devices()
```

and take note of a few potentially valid output devices. In my case it was device 79. The default device is 0, which for me was causing another issue causing a crash.

Next configure the following script with one of the devices you selected above

```
from pyo import *

MY_DEVICE = ## Your Device ID from pa_list_devices()
s = Server(duplex=0)
s.setOutputDevice(MY_DEVICE)
s.boot()

osc = Sine(freq=200).out()

s.gui(locals())
```


Hope this helps!

**Comment by Creepercdn** [comment]
I will try that. My computer install so much virtual audio/midi drivers.

**Comment by Creepercdn** [comment]
Not working too. Errorlevel:-1073741819
MME Output Device(virtual) in device list sample rate:44100hz, but audio settings is 48000hz. virtual audio device panel also set sample rate is 48000hz.
WASAPI Output device sample rate all is 48000hz
WDM-KS OUTput device sample rate same as MME.
I can't find DirectSound device in device list.
WASAPI can't use. It error:
Portaudio error in Pa_OpenStream: Invalid device
Pyo error: From portaudio, Invalid device
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
Pyo error:
Server not booted.

**Comment by Creepercdn** [comment]
I will test pyo in WSL.

**Comment by Steven-Rowell** [comment]
Share the results from the script here: http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html

If that fails to run, can you share the output from the following script

```
from pyo import *

pa_list_devices()
pa_list_host_apis()
```

**Comment by Creepercdn** [comment]
Link is break. I use "Internet archive" to browse it.
I can't run script in http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html.
It error -1073741819
Device/Host List: https://pastebin.com/NyfavYVt
I did try 8 23 33 50, 33 it error invaild number.
I want output to "VoiceMeeter Aux vaio".
It send Processed audio to "Realtek HD Audio output", and send not Processed audio to VoiceMeeter Aux Output.
I don't want use any input device in pyo.

**Comment by belangeo** [comment]
Which version of pyo?
How did you install it?
Did you set `duplex=0`?

**Comment by Creepercdn** [comment]
Pyo 1.0.1
pip install -U pyo
Yes, i set.
s = Server(duplex=0)

**Comment by belangeo** [comment]
Well, I can see anything but unplugging your devices one by one until you find the one that prevent pyo's Server from booting...

**Comment by Creepercdn** [comment]
How i unplug virtual device...

**Comment by belangeo** [comment]
Sorry, I really don't know... I don't use virtual devices.

**Comment by Creepercdn** [comment]
Maybe Disbale in audio settings?

**Comment by Steven-Rowell** [comment]
Try device
```
58: OUT, name: Speakers (VoiceMeeter vaio), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
```

I am also using VoiceMeeter and only my last device worked.

**Comment by Creepercdn** [comment]
Not working.

**Comment by belangeo** [comment]
But be sure that sampling rate and number of channels match with pyo's settings. Another thing to check with WDM-KS is the exclusive mode (if ON, be sure that no other app is already using the audio driver).

**Comment by Creepercdn** [comment]
All device sample rate is 48000hz.
