### ISSUE TITLE
Strange behaviour of square wave modulation

### ISSUE THREAD

**Issue by JeremyKeenan** [belangeo/pyo#176]
I'm using LFO as a modulator in the square wave mode, and I'm noticing that it sounds as if there is a low pass filter on it, so that it is more sinusoid than square. Instead of 'stepped' modulation effect, it sounds like the edges are rounded and there is a smoothed ramp between values.

At first I thought it might the modulation targets I was using having some sort of built-in lag, but I've noticed this effect with oscillators as well as delay and waveguides, so I think the issue is the LFO itself. 

Oscillator:
from pyo import *
s = Server().boot()
s.start()
lf = Sine([.31,.34], mul=15, add=20)
lf2 = LFO(freq = 0.5, sharp = 0, type = 2).range(100, 200)
b = SineLoop(freq = lf2, feedback = 0.12, mul =.2).out()
s.gui(locals())

Pitched feedback delay:
from pyo import *
s = Server().boot()
s.start()
sf = SfPlayer(SNDS_PATH+"/transparent.aif", loop=True, mul=0.3).mix(2).out()
lf = LFO(freq=0.5, type=2).range(0.01, 0.015)
sd = SmoothDelay(sf, delay=lf, feedback=0.8, crossfade=0.05, mul=0.7).out()
s.gui(locals())

Waveguide:
from pyo import *
s = Server().boot()
s.start()

env = HannTable()
m = Metro(Sine(0.01).range(.1,.8), poly=2).play()
tr = TrigRand(m, 0, 1)
te = TrigEnv(m, table=env, dur=.01, mul=.2)

lf1 = LFO(0.1, sharp=0, type=2).range(100,200)
lf2 = LFO(0.3, sharp=0, type=2).range(200,400)
lf3 = LFO(0.4, sharp=0, type=2).range(400,800)
lf4 = LFO(0.5, sharp=0, type=2).range(800,1600)

a = Noise(te)
w = Waveguide(a, freq=[lf1,lf2,lf3,lf4], dur=Sine(3).range(2,20), minfreq=20, mul=.4).out()
s.gui(locals())

**Comment by belangeo** [comment]
Hi,

Yes, the LFO object implements band-limited waveform, so the edges are
rounded... You can do it yourself easily:

phase = Phasor(yourFrequency)
square = (phase < 0.5) * 2 - 1

Olivier

**Comment by JeremyKeenan** [comment]
Thank you Olivier,

Makes perfect sense.

Is the below correct when using .range to map the output of the square wave? Or does range expect values from -1. to 1. ?

phase = Phasor(2.8) 
lf = (phase < 0.5).range(0.005, 0.001)

**Comment by belangeo** [comment]
Hi,

No, range expects a signal from -1 to 1. You can do:

square = (phase < 0.5) * 2 - 1
lf = Sig(square).range(0.005, 0.001)

Olivier
