### ISSUE TITLE
PadSynthTable error

### ISSUE THREAD

**Issue by JeremyKeenan** [belangeo/pyo#177]
I get an error running the documentation example of PadSynthTable.

The Server gui doesn't open at all, and I get the warning: 'Portmidi closed', even though as far as I can tell there is no midi functionality referred to in the code.

I took out the midiToHz(48) in the code and replaced it with an integer, but same issue persists.

I am on Windows 10, Pyo 1.01

code:

from pyo import *

s = Server().boot()
f = s.getSamplingRate() / 262144

t = PadSynthTable(basefreq= 100, spread= 1.205, bw= 10, bwscl= 1.5)
a = Osc(table=t, freq=f, phase= [0, 0.5], mul= 0.5).out()

s.gui(locals())

**Comment by belangeo** [comment]
Fixed in https://github.com/belangeo/pyo/commit/412eb665bdff1b927613f4c088aa3fc0df96e571#diff-da1e04d2a004587aaab9a71ad90be768a5b044b27f55bc3cff0783fa705de1dc
