### ISSUE TITLE
EventInstrument Question

### ISSUE THREAD

**Issue by Steven-Rowell** [belangeo/pyo#178]
There doesn't appear to be any documentation for the `EventInstrument` class.

I thought the following example was more then enough:
https://github.com/belangeo/pyo/blob/00ee25e72b2b722ee2eff03dadaebb1400116d34/pyo/examples/22-events/03-instruments.py

However, after looking at another example which directly sets a `self.output` property I realized
https://github.com/belangeo/pyo/blob/00ee25e72b2b722ee2eff03dadaebb1400116d34/pyo/examples/22-events/14-post-processing.py

I don't think I have an understanding of valid properties for this class. Is there somewhere I can look to better understand how to completely use this class?

**Comment by DataTriny** [comment]
Hi @Steven-Rowell,

You can find `EventInstrument`'s documentation [here](https://github.com/belangeo/pyo/blob/ab2e0dc49f8240b5dcff52aee6da6d67db38e338/pyo/lib/events.py#L181).

It lists the various arguments that are set by the `Events` object and that you can access from the constructor of your own class.

Regarding the output, you are free to store it wherever you want, as you are supposed to start producing a signal directly inside the construcor.

@belangeo I noticed that `EventInstrument` is not mentioned on the event framework's page.

**Comment by Steven-Rowell** [comment]
@DataTriny thanks I was looking at that earlier. 

With that being said I think I might be lacking a fundamental understanding of how this all comes together ha, but I think I'm warming up now. 

Let me know if I'm on the right track here. Looking at this example:

```python
class MyInstrument(EventInstrument):
    def __init__(self, **args):
        EventInstrument.__init__(self, **args)

        # self.freq is derived from the 'degree' argument.
        self.phase = Phasor([self.freq, self.freq*1.003])

        # self.dur is derived from the 'beat' argument.
        self.duty = Expseg([(0, 0.05), (self.dur, 0.5)], exp=4).play()

        self.osc = Compare(self.phase, self.duty, mode="<", mul=1, add=-0.5)

        # EventInstrument created the amplitude envelope as self.env.
        self.filt = ButLP(self.osc, freq=5000, mul=self.env).out()
```

So, `self.phase`, `self.duty`, `self.osc` and `self.filt` are all variables which _dont_ have any significance with regards to the parent class. Next, the output signal from this class comes from: 

```python
 ButLP(self.osc, freq=5000, mul=self.env).out()
```

because of the `::out()` call

**Comment by DataTriny** [comment]
@Steven-Rowell absolutely!

@belangeo I would like to submit a PR adding `EventInstrument` to the documentation but I am not sure whether you would put it on the events page or the base objects one.

Be aware that you listed it on the alphabetical class reference but its description is truncated.

**Comment by belangeo** [comment]
It's added!

http://ajaxsoundstudio.com/pyodoc/api/classes/events.html#eventinstrument

Thanks for pointing that out!

**Comment by Steven-Rowell** [comment]
Going to close this out then! :) 

Worked though all the examples last night and I have a much better understanding of things.

This library is _fantastic_! Thank you all!
