### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by MeinsOE** [belangeo/pyo#180]
I am trying to install pyo but the following error occurs:

   ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files (x86)\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\rieke\\AppData\\Local\\Temp\\pip-install-2e5ercxx\\pyo\\setup.py'"'"'; __file__='"'"'C:\\Users\\rieke\\AppData\\Local\\Temp\\pip-install-2e5ercxx\\pyo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\rieke\AppData\Local\Temp\pip-install-2e5ercxx\pyo\pip-egg-info'
         cwd: C:\Users\rieke\AppData\Local\Temp\pip-install-2e5ercxx\pyo\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rieke\AppData\Local\Temp\pip-install-2e5ercxx\pyo\setup.py", line 204, in <module>
        [os.path.join(data_files_common_path, f) for f in os.listdir(data_files_common_path) if f.endswith(".dll")]),
    FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'win32dlls\\win32_pyo_data_files_common'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by belangeo** [comment]
There is no wheel for python 3.8 32-bit, only 64-bit. If you absolutely need a 32-bit python, there are wheels of pyo for python 3.5, 3.6 and 3.7 32-bit.

**Comment by MeinsOE** [comment]
Ok,thanks
