### ISSUE TITLE
Version 1.0.3 Epyo can't open documentation frame on Win10

### ISSUE THREAD

**Issue by Feihei** [belangeo/pyo#188]
Got two errors:
  File "...\lib\site-packages\pyo\editor\EPyo.py", line 1821, in __init__
    self.Bind(wx.EVT_SEARCH, self.onSearchEnter, id=200)
AttributeError: module 'wx' has no attribute 'EVT_SEARCH'
  File "...\lib\site-packages\pyo\editor\EPyo.py", line 4423, in showDoc
    if not self.doc_frame.IsShown():
AttributeError: 'MainFrame' object has no attribute 'doc_frame'

I'm using miniconda3 and created an env for pyo, with python version 3.8.5, everything was fine with pyo version 1.0.1

**Comment by belangeo** [comment]
Did you upgrade wxpython to 4.1.0?

`pip install -U wxPython
`

**Comment by Feihei** [comment]
OK, I see, it works.
wxpython package is not yet update in conda
