### ISSUE TITLE
FreqShift is backwards

### ISSUE THREAD

**Issue by ultrasound1372** [belangeo/pyo#193]
So as far as I can tell, the shift value in FreqShift is actually backwards. Negative frequencies seem to rise, while positive ones first wrap past 0 and then into negatives, rising there. I've tested this with a sine wave input at 500 Hz, setting the shift value to -500 and to 500, with SigTo. I noticed that when it went from 0 to 500 it went down to 0, when it should have been going up to 1000, as -500 does. Perhaps you're using the wrong sideband?

**Comment by belangeo** [comment]
Fixed!

**Comment by belangeo** [comment]
Fixed in version 1.0.4.
