### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'win64dlls\\win64_pyo_data_files_common'

### ISSUE THREAD

**Issue by BryanWilhite** [belangeo/pyo#196]
Installing `pyo` on Windows 10:

```powershell
py -3.9 -m pip install -U pyo
Collecting pyo
  Using cached pyo-1.0.3.tar.gz (5.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-43cm30gj\\pyo\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-43cm30gj\\pyo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\me\AppData\Local\Temp\pip-pip-egg-info-z86t1y2_'
         cwd: C:\Users\me\AppData\Local\Temp\pip-install-43cm30gj\pyo\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\me\AppData\Local\Temp\pip-install-43cm30gj\pyo\setup.py", line 215, in <module>
        [os.path.join(data_files_common_path, f) for f in os.listdir(data_files_common_path) if f.endswith(".dll")])]
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'win64dlls\\win64_pyo_data_files_common'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Python39\python.exe -m pip install --upgrade pip' command.
```

Does `win64dlls\\win64_pyo_data_files_common` mean anything to you folks?

**Comment by BryanWilhite** [comment]
hey @BryanWilhite just downgrade to [Python 3.7](https://www.python.org/downloads/release/python-379/)

do take [this](http://ajaxsoundstudio.com/pyodoc/download.html#installing-pyo-with-pip) seriously:

>Python supported version are 2.7, 3.5, 3.6 and 3.7.

![image](https://user-images.githubusercontent.com/5226627/96376718-76dbfe80-1135-11eb-8fab-6aa4803d11ea.png)

**Comment by belangeo** [comment]
Pyo 1.0.3 on pypi.org supports 3.6, 3.7 and 3.8. 

https://pypi.org/project/pyo/

Cheers,

**Comment by tvmaly** [comment]
I think the error is here in the setup.py
if sys.platform == "win32":
    if "bdist_wheel" in sys.argv:
        data_files_dest = os.path.join("Lib", "site-packages", "pyo")
    else:
        data_files_dest = "pyo"
>>    data_files_common_path = os.path.join("win64dlls", "win64_pyo_data_files_common")

it is not finding this path  maybe something like this would be better:

dirname = os.path.dirname(__file__)
data_files_common_path = os.path.join(dirname, "win64dlls", "win64_pyo_data_files_common")

**Comment by ThiagoRech1997** [comment]
Collecting pyo
  Using cached pyo-1.0.4.tar.gz (6.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-gzf_vcib\pyo_3e46087734284482b35640e9c3636de3\setup.py", line 293, in <module>
          for f in os.listdir(data_files_common_path)
      FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'win64dlls\\win64_pyo_data_files_common'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by smojef** [comment]
Similar problem with Python 3.10 on Windows.  Was the fix proposed by @tvmaly applied?
```
>py -m pip install --user pyo
Collecting pyo
  Using cached pyo-1.0.4.tar.gz (6.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\me\AppData\Local\Temp\pip-install-6dfei2vg\pyo_8cd029a21437480fbd44637937792377\setup.py", line 293, in <module>
          for f in os.listdir(data_files_common_path)
      FileNotFoundError: [WinError 3] The system cannot find the path specified: 'win64dlls\\win64_pyo_data_files_common'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by smojef** [comment]
I was reading [documentation of pyo 1.0.5](https://belangeo.github.io/pyo/download.html) which says it supports Python up to 3.11 with the command `py -m pip install --user pyo`. However pip only knows pyo up to version 1.0.4.
How can we install pyo 1.0.5?

**Comment by belangeo** [comment]
Wheels for 1.0.5 are on test.pypi for testing right now. You can install with:

py -m pip install --user -i https://test.pypi.org/simple/ pyo
