### ISSUE TITLE
Improving Input latency

### ISSUE THREAD

**Issue by giorgioguttilla** [belangeo/pyo#198]
I'm working on a script that needs responsive input from the microphone (on windows), and am encountering about a half second of delay using the pyo.Input class. This happens both with my default computer soundcard and a Samson C-01 USB microphone. The processing I am attempting to do after receiving input is extremely fast, so it is likely not a problem with CPU speed. Here is a simple example of what I'm trying to do:

`from pyo import *

s = Server(duplex=1, buffersize=512, audio='pa')
s.amp = 0.1
s.boot().start()

a = Input(chnl=1).play().out()

s.gui(locals())`

I tried adjusting buffer size, but nothing seems to affect it. Is this just a problem with my soundcard? Thanks!

**Comment by belangeo** [comment]
By default, pyo uses DIRECTSOUND driver to talk with soundcards, only because it is the most "configuration friendly"! If you are willing to tweak your system, I suggest to take a look at this page in the doc which explain how to use more performant driver like WASAPI or wdm-ks:

http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html

**Comment by gguttilla** [comment]
Thank you! After doing some research and testing on another computer I realized it’s mostly my poor sound card. Buffer size does help to a degree as well. Appreciate it!

**Comment by stripwax** [comment]
Out of interest, is ASIO supported (e.g. in conjunction with ASIO4ALL)?

**Comment by giorgioguttilla** [comment]
I tried to install ASIO4ALL and set audio='asio' but pyo wasn't able to detect it. I might have done somethin wrong in the installation though, I've never used ASIO before.

**Comment by belangeo** [comment]
Run

```
from pyo import *
pa_list_host_apis()
pa_list_devices()

```
to discover what you need to give to the server in order to use ASIO4ALL.

Audio setup functions are documented here: 

http://ajaxsoundstudio.com/pyodoc/api/functions/audio.html

**Comment by belangeo** [comment]
ASIO support is now back in version 1.0.4.
