### ISSUE TITLE
'pip install pyo' is not working?

### ISSUE THREAD

**Issue by Nasko-5** [belangeo/pyo#204]
When i tried to install pyo using pythons package manager pip i get an error.
I dont know what caused it as i dont understand the error it threw.

here it is:

`     ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Me\\AppData\\Local\\Temp\\pip-install-ehyksn05\\pyo_55ac672e7781487e96d355454f9a7442\\setup.py'"'"'; __file__='"'"'C:\\Users\\Me\\AppData\\Local\\Temp\\pip-install-ehyksn05\\pyo_55ac672e7781487e96d355454f9a7442\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Me\AppData\Local\Temp\pip-pip-egg-info-g_uckdzf'
         cwd: C:\Users\Me\AppData\Local\Temp\pip-install-ehyksn05\pyo_55ac672e7781487e96d355454f9a7442\
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Me\AppData\Local\Temp\pip-install-ehyksn05\pyo_55ac672e7781487e96d355454f9a7442\setup.py", line 215, in <module>
        [os.path.join(data_files_common_path, f) for f in os.listdir(data_files_common_path) if f.endswith(".dll")])]
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'win64dlls\\win64_pyo_data_files_common'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by belangeo** [comment]
There is no wheel for python 3.9 yet... And it's unlikely that compiling from sources will work without external dependencies. You should stick with 3.8 for the time being...

**Comment by Nasko-5** [comment]
> There is no wheel for python 3.9 yet... And it's unlikely that compiling from sources will work without external dependencies. You should stick with 3.8 for the time being...

Okay, thank you.
