### ISSUE TITLE
python3.9: undefined symbol: shm_unlink

### ISSUE THREAD

**Issue by pavakhov** [belangeo/pyo#205]
Importerror for pyo: _pyo.cpython-39-x86_64-linux-gnu.so: undefined symbol: shm_unlink

Debian testing recently updated to python3.9.

Thanks all

**Comment by belangeo** [comment]
Can you compile again with the latest source. I added the rt library to the linker on linux, that should fix the problem.

**Comment by pavakhov** [comment]
That seems to work, and Cecilia works as well.  I assume  the "Debian Testing" team/project will pull the update automatically
Thank you

**Comment by belangeo** [comment]
You're welcome! I'll add wheels for python 3.9 in the next release.
