### ISSUE TITLE
Can't Boot Pyo Server

### ISSUE THREAD

**Issue by chigkim** [belangeo/pyo#211]
I'm running MacOS 11.2.1 with Python 3.8.7.
When I run s.boot(), it complains about portaudio, but other libraries like pyaudio that uses portaudio work fine though.

||PaMacCore (AUHAL)|| Error on line 1301: err='-66748', msg=Unknown Error
Portaudio error in Pa_OpenStream: Internal PortAudio error
Pyo error: From portaudio, Internal PortAudio error
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
Pyo error: 
Server not booted.
<pyo.lib.server.Server object at 0x10314a070>

I would appreciate any suggestions.
Thanks!

**Comment by belangeo** [comment]
Pyo has not been tested on Big Sur yet... I should have one within few weeks (months maybe). I'm curious, have you tried booting the server with coreaudio as the backend?

`s = Server(audio="coreaudio").boot()
`

**Comment by chigkim** [comment]
Oh, that worked!

Thanks!

**Comment by jsl303** [comment]
On windows 10 with python 3.7, running "s.boot()" on interactive mode, python just quits without any error.
Any thoughts? Thanks!

**Comment by belangeo** [comment]
@jsl303 What happens if you run the script listed on that page?

http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html

**Comment by jsl303** [comment]
For me what worked was `s = Server(duplex=0)`

**Comment by belangeo** [comment]
@jsl303

> For me what worked was s = Server(duplex=0)

Do you have audio input(s) configured on the system? If so, does audio input have the same number of channels than audio output? If not, the Server has a `ichnls` argument, which can be used to ask for different number of input/output channels.
