### ISSUE TITLE
ASIO4ALL not selectable on Windows PC

### ISSUE THREAD

**Issue by Erwin-Engelsma** [belangeo/pyo#216]
I start up ASIO4ALL and (using offline) I select my Expert Sleepers ES-8 (with expansion card for 16 channels out).
In Python I check for the presence of audio devices using the example program for identifying devices. But ASIO4ALL is not seen. ES-8 is seen, but due to windows settings I can only output 8 channels at most. 
(Using ES-8 to modulate analog modular synths, so having all 16 channels is hugely appreciated).

**Comment by belangeo** [comment]
ASIO support is not included in the portaudio DLL packaged with the latest version of pyo. It's fixed, wiil be available in the next release.

**Comment by belangeo** [comment]
Fixed in version 1.0.4.

**Comment by Erwin-Engelsma** [comment]
This is terrific! Tried it and I got all 16 Channels to work! Thank you.
