### ISSUE TITLE
compile error on linux: `expected ‘(’ before ‘PyType_HasFeature’`

### ISSUE THREAD

**Issue by susca** [belangeo/pyo#217]
## Problem

I tried installing pyo on arch linux in different ways (which probably all do exactly the same), and always get a rather long error, but this seems to be the relevant bit:

```
      In file included from /usr/include/python3.9/pytime.h:6,
                       from /usr/include/python3.9/Python.h:85,
                       from src/objects/bandsplitmodule.c:21:
      src/objects/bandsplitmodule.c: In function ‘MultiBandMain_setFrequencies’:
      /usr/include/python3.9/object.h:633:41: error: expected ‘(’ before ‘PyType_HasFeature’
        633 | #define PyType_FastSubclass(type, flag) PyType_HasFeature(type, flag)
            |                                         ^~~~~~~~~~~~~~~~~
```

## Versions

- Linux 5.11.13-zen1-1-zen #1 ZEN SMP PREEMPT Sat, 10 Apr 2021 20:47:18 +0000 x86_64 GNU/Linux
- gcc 10.2.0
- Python 3.9.3
- anything else of interest that I am missing?

## Steps to reproduce

`poetry add pyo`

or

`pip install pyo`

**Comment by belangeo** [comment]
Hi, it's already fixed in sources.

https://github.com/belangeo/pyo/pull/195

**Comment by susca** [comment]
thank you for the link. I will close this and post there to ask when the fix will reach the pypi package.
