### ISSUE TITLE
Missing a terminator after strncpy in function Server_jack_init, which may cause read-overflow

### ISSUE THREAD

**Issue by Daybreak2019** [belangeo/pyo#221]
### Code snippet
```
Server_jack_init(Server *self)
{
    int i = 0;
    char client_name[32];  -----------> No initialization
    char name[16];
     .........
    strncpy(client_name, self->serverName, 31);  -------------> when length of self->serverName is 31,  client_name may has no terminator. It is a risk of read-overflow.
     .........
}
```

### Description
**Function**:  Server_jack_init
**File**: ad_jack.c
**Call-path**: boot (Python) -> Server_boot -> Server_jack_init 
**WarningType**: read-overflow. Our analysis tool reported a warning at the call-site of strncpy.  As client_name is not initialized, it may has no terminator after strncpy hence to cases read-overflow.
 Also seen in [Details](https://github.com/Daybreak2019/IssueReport/blob/master/Pyo/case-023.png)

**Comment by Daybreak2019** [comment]
Anyone can help confirm this issue? thanks.

**Comment by belangeo** [comment]
I'll take a look as soon as I get a chance. Thanks for reporting.

**Comment by belangeo** [comment]
Fixed. Turns out that the copy was completely useless!

**Comment by Daybreak2019** [comment]
> Fixed. Turns out that the copy was completely useless!

thanks
