### ISSUE TITLE
fails to build or install on Raspberry pi

### ISSUE THREAD

**Issue by steeley** [belangeo/pyo#225]
Pi 4 running raspios 64 buster

pip or build instructions fail:

`aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_PORTAUDIO -DUSE_PORTMIDI -DUSE_OSC -Iinclude -I/usr/include -I/usr/local/include -I/usr/include/python3.7m -c src/engine/pyomodule.c -o build/temp.linux-aarch64-3.7/src/engine/pyomodule.o -Wno-strict-prototypes -Wno-strict-aliasing -O3 -g0 -DNDEBUG
src/engine/pyomodule.c:25:10: fatal error: sndfile.h: No such file or directory
 #include "sndfile.h"
          ^~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1`

**Comment by belangeo** [comment]
Hi,

You're missing libsndfile (and possibly others) dependency. You can install it from the package manager.

see: http://ajaxsoundstudio.com/pyodoc/compiling.html

**Comment by steeley** [comment]
Thanks - I compiled pyo from source and it works with jack now.
