### ISSUE TITLE
pulseaudio not working - linux raspberry pi

### ISSUE THREAD

**Issue by steeley** [belangeo/pyo#227]
in you documentation it refers to pulseaudio:
pa_get_default_devices_from_host(host)

where host can be also,oss,jack,or pulse

my system has pulseaudio woking fine with other apps. it also has jack working with other apps.

PYO can only see Alsa, and oss.

Does pulseaudio work?

**Comment by belangeo** [comment]
Is there an audio input configured in the system? Can you try pyo in output-only mode:

```
s = Server(duplex=0)
```

**Comment by steeley** [comment]
Ahh yes, that was the issue. 
Thanks.
