### ISSUE TITLE
pa_list_devices() return instead of print

### ISSUE THREAD

**Issue by dcardonab** [belangeo/pyo#228]
Hi! First of all, thank you for Pyo, it's awesome and I have been having a blast learning how to use it.

I do have one quick question. Is it possible to get the list that is printed out when running `pa_list_devices()` returned onto a variable? This is so that I can iterate through it looking for a substring to automate connecting to a specific device. When I try any kind of assignment, the variable remains empty (i.e., `available_devices = pa_list_devices()`), and according to the Ajax Sound Studio documentation, the function "Prints a list of all devices found by Portaudio".

Thanks in advance!

**Comment by belangeo** [comment]
Hi David,

You can use *pa_get_input_devices()* and *pa_get_output_devices()* to build
audio device selectors:

http://ajaxsoundstudio.com/pyodoc/api/functions/audio.html#pa-get-input-devices

Olivier

**Comment by dcardonab** [comment]
Thank you very much! Also, thanks for the prompt answer. This is exactly what I needed. :)

~David
