### ISSUE TITLE
Change the default GUI to DearPyGui

### ISSUE THREAD

**Issue by luisArandas** [belangeo/pyo#237]
Hello all,

Thanks for this amazing library. I am wondering how hard would it be to adapt this library to use `DearPyGui` https://github.com/hoffstadt/DearPyGui instead of `Tkinter` or `WxPython`, do you recommend this? If so, where to begin?

Thanks in advance

**Comment by luisArandas** [comment]
Nevermind, I'll just callback the functions by hand

**Comment by belangeo** [comment]
Everything in _wxwidgets.py should be implemented in dearpygui to have the same feature set as with wxpython. Surely possible, but it involves a lot of work. I'm more leaning in the direction of completely removing everything gui-related from pyo, and add them to another, optional, repo that could be pip installed if needed. That way, it would be more cleaner what one need to do to implement a replacement basic GUI for pyo. Still just a thought :)

**Comment by stripwax** [comment]
removing/separating sounds good!
