### ISSUE TITLE
Installing on Win11, Py3.11.0

### ISSUE THREAD

**Issue by GabrieleBattaglia** [belangeo/pyo#253]
Hello. I strongly wish to try this beautiful module but I'm not able to install on Windows 11, under my version of Python which is the 3.11.0
I tried to follow the user guide to install but I have several errors with pip.
How can I do?
Many thanks.
Gabe.

**Comment by belangeo** [comment]
I'll do a release with wheels for python 3.10 and 3.11 in a couple of weeks. For the time being, the best solution is to install python 3.9 and pyo with pip as usual.
Cheers,

**Comment by GabrieleBattaglia** [comment]
Hi Olivier.
I installed Linux as a Windows subsystem via WSL
There I have Python 3.8.10 and I installed succesfully pyo 1.0.4

But when I run it I got the following.

What is the matter?

Thanks.

***@***.***:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> from pyo import *

WxPython is not found for the current python version.
Pyo will use a minimal GUI toolkit written with Tkinter (if available).
This toolkit has limited functionnalities and is no more
maintained or updated. If you want to use all of pyo's
GUI features, you should install WxPython, available here:
http://www.wxpython.org/


Neither WxPython nor Tkinter are found for the current python version.
Pyo's GUI features are disabled. For a complete GUI toolkit, you should
consider installing WxPython, available here: http://www.wxpython.org/

 >>> s=Server().boot()
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function 
snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat 
returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer 
returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or 
directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function 
snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat 
returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer 
returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or 
directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function 
snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat 
returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer 
returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or 
directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function 
snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat 
returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer 
returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or 
directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function 
snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat 
returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer 
returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or 
directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM dmix
Segmentation fault
***@***.***:~$

**Comment by oddwatcher** [comment]
i'm installing your package in python 3.10.9 the microsoft store version ,added /script to PATH
i ran pip install pyo and got the following message:
![屏幕截图_20221209_223635](https://user-images.githubusercontent.com/55705026/206726645-97c8c0bf-6fdb-4471-832d-d1bb371b3226.png)
the chinese in screen is the system cannot find this file
anysolutions?

**Comment by belangeo** [comment]
Wheel files for python 3.10 and 3.11 are coming soon... For the time being, I suggest to stay with python 3.9 (could be installed alongside other versions), that way, you'll get pre-compiled binaries from pip.

**Comment by kfields** [comment]
Wheels for 3.10+ appreciated.  Just commenting to get updates on this issue.  Let me know if you need a beta tester.  Thanks 😊

**Comment by GabrieleBattaglia** [comment]
[# Gabry B:] Waiting for wheel for Python 3.11. I can beta test it. Thanks.

**Comment by ultrasound1372** [comment]
I've got Windows wheels for 3.10 built, but not yet 3.11. WXPython 4.2.0 doesn't build on 3.11 just yet, at least on Windows. I've just opened a PR to fix up some of the paths in the setup.py script to make Windows builds easier. If there aren't yet wheels for 3.10 on pip, I could try and upload them somewhere, presently I only have cp310-cp310-win_amd64

**Comment by GabrieleBattaglia** [comment]
Hi Olivier and all.

Any news on how you release the wheel to install a stable version via 
pip install pyo under Win11 and Python3.11.x?

Awaiting for it since long long time. :)

Gabe.

**Comment by fabiomen10** [comment]
Same here!

**Comment by belangeo** [comment]
It's available since March 2023!

https://pypi.org/project/pyo/#files

**Comment by fabiomen10** [comment]
Thanks for your fast answer @belangeo . It's awesome!

But the error below occurs in my tries of installs.

`PS C:\Users\fabio> pip install pyo
Collecting pyo
  Using cached pyo-1.0.5.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running egg_info
      writing pyo.egg-info\PKG-INFO
      writing dependency_links to pyo.egg-info\dependency_links.txt
      writing entry points to pyo.egg-info\entry_points.txt
      writing top-level names to pyo.egg-info\top_level.txt
      reading manifest file 'pyo.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 419, in <module>
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 596, in add_defaults
          self.read_manifest()
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\sdist.py", line 213, in read_manifest
          self.filelist.append(line)
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 488, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\fabio\AppData\Local\Temp\pip-build-env-6qfp1plx\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/usr/local/Cellar/flac/1.4.2/lib/libFLAC.12.dylib' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by belangeo** [comment]
Hi @fabiomen10 , you're not installing pyo for python 3.11, but for python 3.12. There is no wheels for 3.12 yet. You should stick with 3.11 for the time being.

**Comment by fabiomen10** [comment]
That was it! Thank you very much, once again @belangeo .
