### ISSUE TITLE
Minor bug: In Pyo Server window (wxPython v4.2) if Interpreter input has focus and then clicking on buttons 

### ISSUE THREAD

**Issue by Bibiko** [belangeo/pyo#255]
In `Pyo Server` window (wxPython v4.2) if `Interpreter` input has focus and then clicking on any buttons (Start, Stop, ...) the buttons' state and label are overlapped. If `Interpreter` input looses the focus the buttons are redrawn correctly. I'm on macOS 13.1 (arm).

**Comment by Bibiko** [comment]
This can be fixed in `_wxwidgets.py` > `class ServerGUI(wx.Frame)` (at least for **macOS**).

Instead of initialising `panel` by
`panel = BasePanel(self)`

do it the default way
`panel = wx.Panel(self, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.TAB_TRAVERSAL)`

without setting back/foregroundcolours since with wx 4.2 it's done automatically (at least on macOS).

The issue is, I think, if BackGroundStyle is set to CUSTOM one has to bind wx.EVT_PAINT to a function which draws the panel's background.

**Comment by belangeo** [comment]
Fix is in git.
