### ISSUE TITLE
Wxpython 4.2.0 issue found by usage of Spectrum()

### ISSUE THREAD

**Issue by Bibiko** [belangeo/pyo#256]
It's related to issue #251 for class `RangeSlider` and class `HRangeSlider` in `pyo/lib/_wxwidgets.py`. Any arg of a rect init have to be integers.

Fix (line numbers):
`805 old: midrec = wx.Rect(self.middle - 7, 4, 15, size[1] - 9)`
`805 new: midrec = wx.Rect(int(self.middle - 7), 4, 15, size[1] - 9)`

`943 old: dc.DrawRoundedRectangle(rec[0], rec[1], rec[2], rec[3], 4)`
`943 new: dc.DrawRoundedRectangle(rec[0], rec[1], int(rec[2]), rec[3], 4)`

`949 old: dc.DrawRoundedRectangle(rec[0], rec[1], rec[2], rec[3], 3)`
`949 new: dc.DrawRoundedRectangle(int(rec[0]), rec[1], rec[2], rec[3], 3)`

**Comment by Bibiko** [comment]
it seems safer to enclose all args with `int()`

**Comment by belangeo** [comment]
Done! I'm not on MacOS, but pretty confident it's fixed!

**Comment by Bibiko** [comment]
Thanks!!!
