### ISSUE TITLE
Found bug with stdout during pyo.Server initialization

### ISSUE THREAD

**Issue by smojef** [belangeo/pyo#261]
The following line #768 is problematic:
https://github.com/belangeo/pyo/blob/d705bc8a121a1bdaa849b9711070b82a565b8c20/pyo/lib/_core.py#L765-L770
because it overrides the current `sys.stdout` without prior backup and later assumes it was `sys.__stdout__`.
This actually prevents the `print` statement from working after `pyo.Server()` initialization in special contexts, such as the interactive debugging environment of VS Code and maybe Jupyter Notebooks.

Steps to reproduce:
```python
import sys
import pyo

class StdoutWrapper:
    def __init__(self, stdout):
        self._stdout = stdout

    def write(self, s):
        return self._stdout.write(s)

    def flush(self):
        return self._stdout.flush()

print("Before server init")
print(f" stdout is {repr(sys.stdout)}")

print("Using a non-default stdout")
sys.stdout = StdoutWrapper(sys.stdout)
print(f" stdout is {repr(sys.stdout)}")

prev_stdout = sys.stdout # Saving stdout
server = pyo.Server(sr=8000, nchnls=1, buffersize=256, duplex=False, audio='manual')

print("After Server init")
print(f" stdout is {repr(sys.stdout)}")

assert sys.stdout == prev_stdout
```
Assert will fail:
```
Before server init
 stdout is <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
Using a non-default stdout
 stdout is <__main__.StdoutWrapper object at 0x000001F802F49E10>
After Server init
 stdout is <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
Traceback (most recent call last):
  File "C:\!repos\me_py_hack\DBoxLabRaw\test_pyo_stdout_bug.py", line 27, in <module>
    assert sys.stdout == prev_stdout
AssertionError
```

A recommended fix would be to use a `try / finally` block to save and restore the current `stdout`.

**Comment by stripwax** [comment]
or just use contextlib.redirect_stdout

**Comment by smojef** [comment]
I created pull request #262 using the try/finally approach, but the `contextlib.redirect_stdout` suggestion from @stripwax seems more elegant ;-)

**Comment by belangeo** [comment]
Fixed in master with `contextlib.redirect_stdout`.
