### ISSUE TITLE
Pyo enhancements

### ISSUE THREAD

**Issue by chiaravalle** [belangeo/pyo#270]
Dear Belangeo, 
Please, add to pyo
- Route track (this assumes pyo organizes concurrently playing samples to be on separate, virtual mixer tracks. Such tracks should be able to be routed to one another)
- Still per track, pan and volume
- Reverse a sample or a MIDI event sequence, or an automation clip by the way
- Still same track types, split them by cutting 
- Same tracks except automation, fast/slow motion
- When overlapping audio sources, allow to choose overlap (one excluding the other)  or blend

I hope you will do, I care very much.

Thanks, regards, have a nice day =)

**Comment by belangeo** [comment]
Hi @chiaravalle,

All these features look much more sequencer-oriented than programming-oriented, but let see:

> Route track (this assumes pyo organizes concurrently playing samples to be on separate, virtual mixer tracks. Such tracks should be able to be routed to one another)

It's up to the programmer, not to pyo, to organise its routing as he wishes, but the **Mixer** object is designed to help doing all this!

> Still per track, pan and volume

Can be done very easily after using a Mixer object.

> Reverse a sample or a MIDI event sequence, or an automation clip by the way

- sample: You just have to play it backward, `speed=-1` with **SfPlayer** for example, can also be done with a table.
- Midi sequence: Pyo is a real time, not a sequencer, if you want a MIDI event sequence, you'll have to store your events in a list yourself, and then, you can iterate in any possible way, like in any python list.
- automation clip: This is clearly a sequencer concept, the nearest thing in pyo, is a trajectory stored in a table, and you can read it in many different ways, including backward.
 
> Still same track types, split them by cutting
> Same tracks except automation, fast/slow motion

Again, these are sequencer-oriented processes, not programming-oriented.

> When overlapping audio sources, allow to choose overlap (one excluding the other) or blend

You surely can done any type of blending, overlapping, cross-fading, etc. with pyo. There are plenty of envelope types, and cross-fading functionalities.

**Comment by chiaravalle** [comment]
Please, excuse me.
I misinterpreted the library.

By the way, your attempt to please me anyhow deserve kudos, that's for sure!!!

Thanks a lot.
