### ISSUE TITLE
Python 3 (feature request)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [belangeo/pyo#40]
```
Hi,

Will there be Python 3 support?

Python 3 is now the official Python version (and is well on its way to replace 
Python 2). See: http://www.python.org/

Please add Python 3 support! Thank you.

Best regards,
Alexander Rødseth
```

Original issue reported on code.google.com by `rods...@gmail.com` on 9 Dec 2012 at 10:00

**Comment by Twangist** [comment]
+1
It's almost a bug report now.

**Comment by milkmiruku** [comment]
Compiling fails on systems where Python 3 is default;
 
    src/engine/listenermodule.c: In function ‘MidiListener_dealloc’:
    src/engine/listenermodule.c:309:9: error: ‘MidiListener {aka struct <anonymous>}’ has no member named ‘ob_type’
         self->ob_type->tp_free((PyObject*)self);
             ^
The fix for that is to altering the compile/install command to `python2`.

**Comment by jmmcd** [comment]
I got the error
```
"error: no member named 'ob_type' in 'Stream'"
```
when compiling with Python 3. Just adding this in case it helps the next person arrive at the right bug report.

**Comment by azzurolilc** [comment]
+1 been a year any updates?
