### ISSUE TITLE
Unable to install PYO in OS X

### ISSUE THREAD

**Issue by snailrowen** [belangeo/pyo#64]
I try to install PYO on my yosemite OS X, but I keep on getting the error below. I'm not sure what I should do - any tips?

Best,
Johan

$$
Johans-MacBook-Pro:pyo johanbjorck$ brew install python liblo libsndfile portaudio portmidi --universal
Warning: python-2.7.10_2 already installed
Warning: liblo-0.28 already installed
Warning: libsndfile-1.0.25 already installed
Warning: portaudio-19.20140130 already installed
==> Downloading https://downloads.sourceforge.net/project/portmedia/portmidi/217
Already downloaded: /Library/Caches/Homebrew/portmidi-217.zip
==> Patching
patching file pm_common/CMakeLists.txt
==> make -f pm_mac/Makefile.osx
Last 15 lines from /Users/johanbjorck/Library/Logs/Homebrew/portmidi/01.Makefile.osx:
[ 68%] Linking C executable ../latency
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [midithread] Error 1
make[2]: *** [pm_test/CMakeFiles/midithread.dir/all] Error 2
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [midiclock] Error 1
make[2]: *** [pm_test/CMakeFiles/midiclock.dir/all] Error 2
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [latency] Error 1
make[2]: *** [pm_test/CMakeFiles/latency.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

Johans-MacBook-Pro:pyo johanbjorck$ 
$$

**Comment by belangeo** [comment]
Hi,
Seems more to be a question for homebrew of portmidi devs... You should try to post on their forum.
You can also install pyo with the binary installer (that will install all needed dependencies).
http://ajaxsoundstudio.com/software/pyo/
Olivier
