### ISSUE TITLE
problem with  _core module

### ISSUE THREAD

**Issue by vdlg** [belangeo/pyo#66]
Hi,

I installed pyo-0.7.7 using Homebrew following the instructions in 

http://ajaxsoundstudio.com/pyodoc/compiling.html 
     
When I try to run the pyo.py module or any of the examples in pyo/examples I get the same following error 
 
Traceback (most recent call last):
  File "01_music_box.py", line 8, in <module>
    from pyo import *
  File "//anaconda/lib/python2.7/site-packages/pyo.py", line 21, in <module>
    import pyolib.analysis as analysis
  File "//anaconda/lib/python2.7/site-packages/pyolib/analysis.py", line 30, in <module>
    from _core import *
  File "//anaconda/lib/python2.7/site-packages/pyolib/_core.py", line 32, in <module>
    from _pyo import *
ImportError: No module named _pyo

This actually appends whenever using the _core module. 
 
Any help would be greatly appreciated ! 

Many thanks !

**Comment by leobarn** [comment]
Hello,

I had the same problem. I solved it this way.

Go to the web-site http://ajaxsoundstudio.com/software/pyo/
Download the binary and install it.

After you install it you have to copy some files to your python 2.7 compiler directory structuur.

copy the files:
c:\Python271\Lib\site-packages\_pyo.pyd
c:\Python271\Lib\site-packages\_pyo64.pyd

to

c:\Python27\DLLs\

and copy all the libraries to this directory.

c:\Python27\DLLs\

After these operations try again.

Met vriendelijke groet, kind regards, 
 
Leo Barnhoorn

**Comment by wjimena** [comment]
Hi,
 
thanks for the help ! 

Indeed the pyo files and libraries were not in the right place. They must be located in the site-packages folder corresponding to the python distribution that you are used. In my case the default distribution was   
the Python 2.7 from Anaconda (https://www.continuum.io/downloads) and not the one installed with brew, so I moved  

_pyo64.so
pyo64.py
_pyo.so
pyo.py
redirect.pth
pyolib/

from 

/Library/Python/2.7/site-packages

to

/anaconda/lib/python2.7/site-packages.

Now it works fine :)

Cheers !
