### ISSUE TITLE
windows 10 64bit

### ISSUE THREAD

**Issue by matt-erhart** [belangeo/pyo#73]
I'd like to install pyo on windows 10 64bit. I get the following error with the 32bit.exe when I try and import pyo: 

ImportError: DLL load failed: %1 is not a valid Win32 application.

What's recommended to solve this?

**Comment by Ajk4** [comment]
From this issue https://github.com/belangeo/pyo/issues/115 it seems like 64bit is not supported.

Unfortunetely it is a blocker for me. You could really consider releasing 64 bit version for Windows since it will be a standard eventually.

**Comment by belangeo** [comment]
Pyo is now compiling under Windows with python 64-bit. This will be part of the next release.
