### ISSUE TITLE
Jack doesn't fully quit on Ubuntu 14.04, blocks system audio

### ISSUE THREAD

**Issue by dantheman39** [belangeo/pyo#74]
Hello, I installed the latest version following the instructions on your web page (0.7.9), (although I didn't install python-wxgtk3.0 because it's not in the 14.04 repositories, I'm figuring that won't affect things here since I'm using the command line, but correct me if I'm wrong. It compiled with no errors). The problem is that after stopping the server and then quitting python, jack doesn't fully quit, which means that the audio card is locked up and my system has no sound until I run 'killall jackd' at the command line.

I ran the quick start from the website from the python console, specifying audio='jack':
```python
from pyo import *
s = Server(audio='jack').boot()
s.start()
a = Sine(mul=0.01).out()
s.stop()
```

I get the following messages:
\>\>\>from pyo import *
pyo version 0.7.9 (uses single precision)

\>\>\>s = Server(audio='jack').boot()
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2013 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
Sample rate set to Jack engine sample rate: 48000
Buffer size set to Jack engine buffer size: 1024

\>\>\> s.start()
<pyolib.server.Server object at 0x7f92fcb4ff50>
\>\>\> a = Sine(mul=0.01).out()
\>\>\> s.stop()
\>\>\> quit()
JackTemporaryException : now quits...

Thank you very much for the program!

**Comment by belangeo** [comment]
If you ask for jack as the audio backend and jack is not already started, pyo will start it. But pyo will never ask jack to automatically stop, it's the user responsability (who knows, maybe there is a bunch of apps using jack at the same time).

**Comment by dantheman39** [comment]
That makes total sense! I guess the only thing I might add as a suggestion
for improvement would be to mention this somewhere in the docs. Thanks!

**Comment by belangeo** [comment]
Done in git.
