### ISSUE TITLE
Calling script file from embedded pyo (m_pyo.h)

### ISSUE THREAD

**Issue by ghost** [belangeo/pyo#75]
When using pyo_exec_file(...) with an error in it, the function never returns.

This  return an error (which is what expected) : 

```
bat_de_baseball();
sine = Sine(freq=1000, mul=1.0, add=0.0)
```

This too : 

```
sine = Sine(freq=1000, mul=1.0, add=0.0);
chat();
```

**But this never goes out of the function** :
`sine = Sine(freq=1000, mul=1.0, add=0.0).ballon_de_soccer();`

All of them return an error when using from terminal `python name_of_file.py`

Any idea why ?

**Comment by belangeo** [comment]
Fixed.
