### ISSUE TITLE
weird install location

### ISSUE THREAD

**Issue by pierodancona** [belangeo/pyo#76]
Hi. Mac OS X.11.4. Downloaded installer and install pyo.
It takes a very long time to install (10 min). 
No good, import can not find pyo. 
I look around for it and I find it in /tmp/python27.
Before I start messing around, is this a know issue?
What's wrong?
Thxbye

**Comment by belangeo** [comment]
The only thing I can think of is a problem with the password given during installation process... Indeed, the installer puts the files in /tmp/python26 and /tmp/python27. From there, the postinstall script copy the files to the different python version site-packages directories and delete /tmp/python2*. All these commands are executed as sudo and obviously they failed... Did you try re-running the installer?

Olivier.

**Comment by holdenweb** [comment]
Given the use of `sudo` and the provision of Mac installer (`.dmg` files) I am wondering how well-suited to running in virtual environments `pyo` might be. I know from experience that wxPython is not well-suited to virtualenvs. The package's existence is quite an achievement, so I don't want readers to think I am carping here, but are there any plans to accommodate multiple installations in different virtual environments?

**Comment by belangeo** [comment]
As it is right now, I don't think pyo can be used in virtualenv without modifications. The compilation process definitely searches headers files in the system tree. That should not be too hard to adapt... There is also a concern about third-party dependencies (portaudio, portmidi, libsndfile, liblo). Will a pyo running inside a virtualenv will be able to find these dynamic libraries in standard paths? Will do some testing as soon as I have some time...

**Comment by holdenweb** [comment]
Thanks. I realize this will be a significant effort, and therefore probably not an immediate priority.

**Comment by belangeo** [comment]
Next release will be installed with pip. This will be no more an issue.

**Comment by holdenweb** [comment]
Wonderful - great work. Thanks very much.
