### ISSUE TITLE
SIGSEGV when multiplying a number and a base object

### ISSUE THREAD

**Issue by DrPyser** [belangeo/pyo#78]
Doing an operation such as `1.5*Sine()[0]` result in a `SIGSEGV (address boundary error)`.
I ran into this problem when dealing with Channel Expansion when creating a class. 
Example:

```
freq, mul, lmax = convertArgsToLists(freq,mul)
mod = Sine(freq=[wrap(freq,i)*wrap(mul,i) for i in range(lmax)])
```

Here, if `freq` was a number(or a list of number), and `mul` was a pyo object, `wrap` will return a base object for `mul`, and this will result in a `SIGSEGV`.

**Comment by belangeo** [comment]
XXX_base object can't handle reverse math op. The XXX_base object should be first:

a = 1.5 * Sine()[0] # wrong
a = Sine()[0] * 1.5 # ok

You should really let pyo objects handle multi-channel expansion. Working and simplified version:

freq = 400
mul = Sig([random.uniform(.98,1.02) for i in range(4)])
mod = Sine(freq=freq*mul, mul=0.1)

**Comment by HalfVoxel** [comment]
Throwing a SIGSEGV seems unreasonable to do in this case though. If support for reverse math ops cannot be implemented easily, maybe just throw a descriptive error message instead?

**Comment by belangeo** [comment]
I don't think I have any power on this... It is a number object receiving a wrong type for its math operator. I can't find anything like python's __rmul__ in the C API.
