### ISSUE TITLE
SigTo time control

### ISSUE THREAD

**Issue by pabloriera** [belangeo/pyo#87]
Hi, I wonder if is possible to control the portamento time of SigTo with midi control.

```
porta = Midictl(ctlnumber=[79], minscale=0., maxscale=60.)
pos = SigTo( posx , time=porta)
```

I tried this but doesn't work, as time should be a float

Thanks!

**Comment by belangeo** [comment]
That was an easy one! I've added the control of SigTo ramp time at audio rate in the sources. If you can't compile pyo from sources, until the next release (very soon), you can do something like this:

porta = Midictl(ctlnumber=[79], minscale=0., maxscale=60.)
pos = SigTo(posx)

def set_ramp_time():
    pos.time = porta.get()

tf = TrigFunc(Change(porta), function=set_ramp_time)

**Comment by pabloriera** [comment]
Excellent! thanks a lot
