### ISSUE TITLE
Cannot pass tuple as arg in TrigFunc

### ISSUE THREAD

**Issue by DrPyser** [belangeo/pyo#90]
Not sure if this is normal expected behavior or a real bug, but intuitively I should be able to pass a tuple as the 'arg' to `TrigFunc`, so that the function can be called with multiple arguments...

When I try that, it complains:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drpyser/repositories/pyo/pyolib/custom/probabilistic.py", line 24, in <module>
    a = TrigFunc(m, function=lambda (x,y,z):val.setValue(x), arg=(1,2,3))
  File "/home/drpyser/.local/lib/python2.7/site-packages/pyolib/triggers.py", line 1142, in __init__
    self._base_objs = [TrigFunc_base(wrap(in_fader,i), WeakMethod(wrap(function,i)), wrap(arg,i)) for i in range(lmax)]
TypeError: setArg() takes exactly one argument (3 given)
```

**Comment by belangeo** [comment]
I'll see what I can do... In the mean time, you can wrap your tuple in a structure that does not expand as arguments and restore it in the function:

def ff(x):
    tup = eval(x)
    
tf = TrigFunc(Trig(), ff, str((1,2,3)))
