### ISSUE TITLE
SfMarkerShuffler and SfMarkerLooper jump to the wrong position

### ISSUE THREAD

**Issue by hilbrichtsoftware** [belangeo/pyo#93]
Provided with this bug report is an .aiff file (zipped for github reasons)
[bugreport.zip](https://github.com/belangeo/pyo/files/790719/bugreport.zip)

It consists of four parts that are capable of sample accurate looping. in fact I combined them myself. The markers are at [0, 162831, 976985, 1139816] and have ids 1-4. 
The markers / frame positions themselves are correct. You can check by using external tools, e.g. sox:
`sox test.aiff out.aiff trim 0 162831s `
which results in a new file with only the first part, which is perfectly loopable. This can be verified even by ear when using pyos SfPlayer with loop=True. 

However, using either SfMarkerShuffler or SfMarkerLooper with the provided file results in wrong playback. For example the first chunk is too short.  Here is a short code to try it out. The listening result should be a pleasant loop of exactly 8 kick-drum beats without any hiccups. But the loop jumps back too early. 
It doesn't matter which mark is used or if you use the Shuffler instead. (For my program I need the shuffler, but looper is easier to demonstrate here)

Additional Information: My server runs at 48000 Hz but the file is 44100 Hz.  I have not looked at your code yet but I assume you apply resampling to the mark positions as well?

```
#! /usr/bin/env python3
# -*- coding: utf-8 -*-
import pyo
server = pyo.Server(audio="jack", nchnls=2, duplex=0, jackname="rpp", ichnls=0)
server.setJackAuto(xin=False, xout=True)
server.deactivateMidi()
server.boot()

aiffFile = "bugreport.aiff"
sf = pyo.SfMarkerLooper(aiffFile, mark=1).out()
server.gui(locals())
```

**Comment by hilbrichtsoftware** [comment]
I just confirmed my initial suspicion by starting jack with 44100Hz 

The marks from the aiff need resampling as well.

**Comment by belangeo** [comment]
Fixed in git. Thanks for reporting!
