### ISSUE TITLE
SfPlayer not playing, cleaned up before started?

### ISSUE THREAD

**Issue by matthijskooijman** [belangeo/pyo#95]
I tried playing some sound from a script, which didn't work. Looking more closely, the streams got cleaned up directly after creating them, making me believe the SfPlayer object is getting destroyed by the python runtime because I wasn't storing any reference to it. Storing the SfPlayer object into a variable made the player play as expected, confirming this theory. However, once the variable goes out of scope, or its value gets overwritten by something else (such as another SfPlayer object) stops the player again.

I was hoping to use pyo for playing some fire-and-forget audio samples, which now requires tracking these SfPlayer objects (and probably watching their triggers to clean them up when done). I was hoping that pyo would handle this stuff for me.

Am I doing something wrong, or is this a missing feature from the library?

I would expect that starting playback would keep the object alive, and looking at the sources this actually seems intended: https://github.com/belangeo/pyo/blob/master/include/pyomodule.h#L1662 but apparently that doesn't work. Thinking about it again, I think the incref is because the value is returned, not because it is playing. Especially since STOP doesn't DECREF either.

Would this be a matter of adding an INCREF in OUT (and PLAY?) and a DECREF in STOP? There should also be a DECREF when the song is finished (if loop is false), but I couldn't find where this is handled.

**Comment by matthijskooijman** [comment]
Oh, here's the code I was using. Running python3 and yesterday's git master of pyo:

```
import pyo
import time

s = pyo.Server(duplex=0)
s.setVerbosity(15)
s.boot()
s.start()

pyo.SfPlayer("sounds/sound.wav").out()

time.sleep(100)
```

**Comment by belangeo** [comment]
Yes, it's the responsibility of the user to keep reference of his objects as long as he needs them... There is no way for pyo to know when an object is no more needed. An SfPlayer can be started/stopped many times in a single performance, with the same or different sounds. Maybe that's what you should do, use just a few SfPlayer objects and change their sound path and start them as needed:

    sf = pyo.SfPlayer(path_to_sound)

    def go(path_to_sound) :
        sf.path = path_to_sound
        sf.out()

**Comment by matthijskooijman** [comment]
I was hoping to prevent the bookkeeping associated with keeping a list of players, figuring out which is free, etc. I've since switched to pygame instead (IIRC I ran into some other problem involving python2 vs python3 or something), so it's not exactly relevant for me anymore.

> There is no way for pyo to know when an object is no more needed.

But it does try to know this, since it cleans up the object when all references are gone. My suggestion would be to not clean up running players, and treat the "is running" as an extra reference. Once playing stops, this reference is removed and the object can be cleaned up as normal. That would make these player objects a lot more useful for fire-and-forget type of usage.

**Comment by belangeo** [comment]
Ok, I see your point... I'll have to think about this because I want the same behavior for all objects in the lib. The "is running" as an extra reference (I like the idea of fire-and-forget usage) implies that every objects have to be explicitly stopped to be garbage-collected (I don't like this very much!). I'll keep this issue opened as a reminder...!

**Comment by belangeo** [comment]
It's definitively the role of the python interpreter to manage garbage collection and the user is responsible for keeping track of his objects. A pyo object should be started/stopped as needed (may be many times), so it can't be garbage-collected on an "is-running" basis. I close this issue as nothing will be done about this.
