### ISSUE TITLE
Does pyo work with python 3.4?

### ISSUE THREAD

**Issue by VitamintK** [belangeo/pyo#96]
Tried installing with binary for python 3 on windows, but it didn't work.  I have 32-bit python 3.4, and the installer looks like it says 3.5, so is this the reason?

Works for me if I use the 2.7 installer with my installation of 2.7.

The error I got for python 3 after installation was: `ImportError: No module named _pyo`.

![image](https://cloud.githubusercontent.com/assets/1139798/25776111/f30e0bc8-3269-11e7-86e7-1b5735d7143a.png)

I also tried following the instructions in #66, by moving `_pyo.cp35-win32.pyd` and `_pyo64.cp35-win32.pyd` from `C:\Python34\Lib\site-packages` to `C:\Python34\DLLs`, and renaming them to `_pyo.pyd` and `_pyo64.pyd`, after which the error became `ImportError: DLL load failed: The specified module could not be found.`

Any help would be appreciated.

edit: Also, I am on a 64-bit windows system, but both my 2.7 and 3.4 python installations are 32-bit.

**Comment by belangeo** [comment]
You can't just copy the files from one python version to another... The binairies must be used with the python version it was built with... I'm planning to move up to python 3.6 this summer.
