### ISSUE TITLE
The Server must be booted!

### ISSUE THREAD

**Issue by YoomarXD** [belangeo/pyo#99]
Hi, I just installed pyo for Python 2.7 on Windows 10.

By running  the code given by the [doucmentation](http://ajaxsoundstudio.com/pyodoc/gettingstarted.html) 
```
from pyo import *
s = Server().boot()
s.start()
a = Sine(mul=0.01).out()
s.gui(locals())
```

Throws me the next output:
```
pyo version 0.8.6 (uses single precision)
Traceback (most recent call last):
  File "D:/OneDrive/Documents/Python/prubas/pyo test.py", line 4, in <module>
    a = Sine(mul=0.01).out()
  File "C:\Program Files (x86)\Python 2.7\lib\site-packages\pyolib\generators.py", line 60, in __init__
    PyoObject.__init__(self, mul, add)
  File "C:\Program Files (x86)\Python 2.7\lib\site-packages\pyolib\_core.py", line 748, in __init__
    PyoObjectBase.__init__(self)
  File "C:\Program Files (x86)\Python 2.7\lib\site-packages\pyolib\_core.py", line 590, in __init__
    raise PyoServerStateException("The Server must be booted before "
pyolib._core.PyoServerStateException: The Server must be booted before creating any audio object.
portaudio error in Pa_OpenStream: Invalid device
Portaudio error: Invalid deviceportaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized

Server not booted.
Portmidi closed.
The Server must be booted!
```

Am I doing something wrong?

**Comment by belangeo** [comment]
AFAICT, here is what can cause this portaudio issue (pyo now defaults WASAPI):

1) No audio input configured on the system (workaround is duplex=0)
2) Audio input and output driver have different sampling rates
(indeed, pyo must use the same).
3) Audio device "exclusive access" is checked in system preferences
and another software already uses the device.

4) If nothing works, you can try another host: Server(winhost="asio")
or Server(winhost="mme"), or change the device
numbers: Server.setInputDevice(x) and Server.setOutputDevice(x). See
pa_list_devices() for the complete list of available devices.

**Comment by YoomarXD** [comment]
THANK YOU!

**Server(winhost="mme")** fixed it.

You should add that to the documentation :)

**Comment by belangeo** [comment]
In my TODO!
